/*									tab:4
 *
 * "Copyright (c) 2001 and The Regents of the University 
 * of California.  All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice and the following
 * two paragraphs appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF
 * CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
 */

TOS_MODULE SLEEP_TEST;
/* Interface definition corresponds to component SLEEP_TEST port 
   definition in vhd file.  Name matching, not position. 
   Pin Interface is not mentioned.
*/

ACCEPTS{
	char SLEEP_TEST_INIT(void);
	char SLEEP_TEST_START(void);
};

SIGNALS{
};

HANDLES{
	void SLEEP_TEST_CLOCK_EVENT(void);
	char SLEEP_TEST_DATA_EVENT(int data);
	char SLEEP_TEST_SUB_MSG_SEND_DONE(TOS_MsgPtr msg);
	TOS_MsgPtr SLEEP_TEST_MSG(TOS_MsgPtr data);
	void SLEEP_TEST_WAKEUP();
};

USES{
	char SLEEP_TEST_SUB_INIT(void);
	char SLEEP_TEST_CLOCK_INIT(char interval, char scale);
	char SLEEP_TEST_SUB_SEND_MSG(short addr,char type, TOS_MsgPtr data);
	char SLEEP_TEST_SUB_PWR(char pwr);
	char SLEEP_TEST_GET_DATA(void);
	char SLEEP_TEST_LEDy_on(void);
	char SLEEP_TEST_LEDy_off(void);
	char SLEEP_TEST_LEDr_on(void);
	char SLEEP_TEST_LEDr_off(void);
	char SLEEP_TEST_LEDg_on(void);
	char SLEEP_TEST_LEDg_off(void);
	char SLEEP_TEST_SLEEP_INIT(unsigned short timeout);
};

