<?php

define("NUCLEUS_XMLRPC_SERVER", "omega.cs.berkeley.edu");
define("NUCLEUS_XMLRPC_SERVER_PORT", "8080");
define("NUCLEUS_XMLRPC_SERVER_PATH", "/");
define("NUCLEUS_XMLRPC_SERVER_TIMEOUT", 2);

define("NUCLEUS_UPLOAD_DIRECTORY", "/tmp");

define("NUCLEUS_DEFAULT_QUERY_DELAY", 10);

define("SIMULATED_QUERY", 0);
define("SIMULATED_MOTE_SIZE", 1000);
define("SIMULATED_MOTE_FAILURE", 5); //percent


?>
