// $Id: MSP430GeneralIO.h,v 1.1.1.1 2007/11/05 19:10:15 jpolastre Exp $

/* "Copyright (c) 2000-2003 The Regents of the University of California.  
 * All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement
 * is hereby granted, provided that the above copyright notice, the following
 * two paragraphs and the author appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY
 * OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
 */

// @author Cory Sharp <cssharp@eecs.berkeley.edu>

#ifndef _H_MSP430GeneralIO_h
#define _H_MSP430GeneralIO_h

TOSH_ASSIGN_PIN(PORT10,1,0);
TOSH_ASSIGN_PIN(PORT11,1,1);
TOSH_ASSIGN_PIN(PORT12,1,2);
TOSH_ASSIGN_PIN(PORT13,1,3);
TOSH_ASSIGN_PIN(PORT14,1,4);
TOSH_ASSIGN_PIN(PORT15,1,5);
TOSH_ASSIGN_PIN(PORT16,1,6);
TOSH_ASSIGN_PIN(PORT17,1,7);

TOSH_ASSIGN_PIN(PORT20,2,0);
TOSH_ASSIGN_PIN(PORT21,2,1);
TOSH_ASSIGN_PIN(PORT22,2,2);
TOSH_ASSIGN_PIN(PORT23,2,3);
TOSH_ASSIGN_PIN(PORT24,2,4);
TOSH_ASSIGN_PIN(PORT25,2,5);
TOSH_ASSIGN_PIN(PORT26,2,6);
TOSH_ASSIGN_PIN(PORT27,2,7);

TOSH_ASSIGN_PIN(PORT30,3,0);
TOSH_ASSIGN_PIN(PORT31,3,1);
TOSH_ASSIGN_PIN(PORT32,3,2);
TOSH_ASSIGN_PIN(PORT33,3,3);
TOSH_ASSIGN_PIN(PORT34,3,4);
TOSH_ASSIGN_PIN(PORT35,3,5);
TOSH_ASSIGN_PIN(PORT36,3,6);
TOSH_ASSIGN_PIN(PORT37,3,7);

TOSH_ASSIGN_PIN(PORT40,4,0);
TOSH_ASSIGN_PIN(PORT41,4,1);
TOSH_ASSIGN_PIN(PORT42,4,2);
TOSH_ASSIGN_PIN(PORT43,4,3);
TOSH_ASSIGN_PIN(PORT44,4,4);
TOSH_ASSIGN_PIN(PORT45,4,5);
TOSH_ASSIGN_PIN(PORT46,4,6);
TOSH_ASSIGN_PIN(PORT47,4,7);

TOSH_ASSIGN_PIN(PORT50,5,0);
TOSH_ASSIGN_PIN(PORT51,5,1);
TOSH_ASSIGN_PIN(PORT52,5,2);
TOSH_ASSIGN_PIN(PORT53,5,3);
TOSH_ASSIGN_PIN(PORT54,5,4);
TOSH_ASSIGN_PIN(PORT55,5,5);
TOSH_ASSIGN_PIN(PORT56,5,6);
TOSH_ASSIGN_PIN(PORT57,5,7);

TOSH_ASSIGN_PIN(PORT60,6,0);
TOSH_ASSIGN_PIN(PORT61,6,1);
TOSH_ASSIGN_PIN(PORT62,6,2);
TOSH_ASSIGN_PIN(PORT63,6,3);
TOSH_ASSIGN_PIN(PORT64,6,4);
TOSH_ASSIGN_PIN(PORT65,6,5);
TOSH_ASSIGN_PIN(PORT66,6,6);
TOSH_ASSIGN_PIN(PORT67,6,7);

#endif//_H_MSP430GeneralIO_h

