COMPONENT=MediaFormatC

# FlashBridge directories
CFLAGS += -I../../interfaces

# Utils
CFLAGS += -I../../../../../tos/lib/State 
CFLAGS += -I../../../../../tos/lib/GenericCrc

## Choose a flash type:
#CFLAGS += -I../../media/at45db
CFLAGS += -I../../media/stm25p

# If you are using Boomerang, uncomment the following line:
#CFLAGS += -DSTM25P_BOOMERANG_VERSION

include $(MAKERULES)
