include ../Makelocal
FIREBOARD_PATH += -I$(MTS420CA)/sensors/taos_tsl250rd
LOCAL_PATH += $(FIREBOARD_PATH)

COMPONENT=testtaos
PFLAGS := $(LOCAL_PATH) $(LOCAL_DEFINES) $(PFLAGS)

include $(TOSROOT)/apps/Makerules

