

include ../Makelocal
FIREBOARD_PATH += -I$(MTS420CA)/sensors/sensirion_sht11
LOCAL_PATH += $(FIREBOARD_PATH)

COMPONENT=testsensirion

PFLAGS := $(LOCAL_PATH) $(LOCAL_DEFINES) $(PFLAGS)

include $(TOSROOT)/apps/Makerules
