#!/bin/bash
# this is going to initialise the database, create directory pgdata
# start the postmaster and do createdb
# see if i need to run ipc-daemon
echo ">> I am assuming you have pgsql and ipc-daemon install"
echo ">> I am going to create pgdata in your home directory"
echo ">> Please Enter your password as 'blah'"
echo ""

ipc_running=`ps | grep 'ipc-daemon'`
if [ -z "$ipc_running" ]; then
  ipc-daemon &
fi


pgdata_path=$HOME/pgdata
if [ -d $pgdata_path ]; then
  rm -rf $pgdata_path
fi
initdb -W -D $pgdata_path
./startdb
