        agents[0].id.id = getNewID();
        agents[0].pc = 0;
        agents[0].state = AGILLA_STATE_READY;
        call CodeMgrI.allocateBlocks(&agents[0], 15);
        dbg(DBG_USR1, "||||||||||||||||||||||||||||||||||||||||||||||||||||||||\n");
        dbg(DBG_USR1, "Running Bounce0to1.ma\n");
        cMsg.msgNum = 0;
        cMsg.code[0] = IOPpushc | 25;
        cMsg.code[1] = IOPputled;
        cMsg.code[2] = IOPpushc | 2;
        cMsg.code[3] = IOPsleep;
        cMsg.code[4] = IOPpushc | 25;
        cMsg.code[5] = IOPputled;
        cMsg.code[6] = IOPaddr;
        cMsg.code[7] = IOPpushc | 0;
        cMsg.code[8] = IOPcneq;
        cMsg.code[9] = IOPrjumpc | 5;
        cMsg.code[10] = IOPpushc | 1;
        cMsg.code[11] = IOPwmove;
        cMsg.code[12] = IOPpushc | 28;
        cMsg.code[13] = IOPputled;
        cMsg.code[14] = IOPhalt;
        call CodeMgrI.setBlock(&agents[0], &cMsg);
