/* Generated By:JavaCC: Do not edit this line. CompParserConstants.java */
package net.tinyos.compparser;

public interface CompParserConstants {

  int EOF = 0;
  int MODULE = 8;
  int ACCEPTS = 9;
  int HANDLES = 10;
  int USES = 11;
  int SIGNALS = 12;
  int INTERNAL = 13;
  int JOINTLY = 14;
  int IMPL = 15;
  int IDENTIFIER = 16;
  int LETTER = 17;
  int DIGIT = 18;
  int TYPE = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"TOS_MODULE\"",
    "\"ACCEPTS\"",
    "\"HANDLES\"",
    "\"USES\"",
    "\"SIGNALS\"",
    "\"INTERNAL\"",
    "\"JOINTLY\"",
    "\"IMPLEMENTED_BY\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<TYPE>",
    "\";\"",
    "\"{\"",
    "\"};\"",
    "\"(\"",
    "\");\"",
    "\",\"",
  };

}
