# For this copy in minitasks/03/uva/EnviroTrack/, I've deleted and
# modified files so that it compiles only when the EnviroTrack is in
# minitasks/03/ucb/.  You can accomplish this by originally checking it
# out in the uva/ directory then just moving EnviroTrack to the ucb/
# directory.  Don't worry, CVS will do the right thing for commits.

COMPONENT=Enviro
#SENSORBOARDS=honeydot
SENSORBOARDS=micasb
include ../Makerules

