#define SCATTERNET_FORMATION_COMMAND 0x40
#define ROUTE_DISCOVERY_COMMAND      0x80

typedef enum {
  COMMAND_NULL,
  COMMAND_NEW_NODE_CONNECTION,
  COMMAND_NODE_DISCONNECTION,
  COMMAND_NETWORK_DISCOVERY_DISABLED,
  APP_QUERY_SENSOR_DATA, // not a good implementation - look into TinyDB port
  APP_REPLY_SENSOR_DATA,
  APP_LOG_MESSAGE,
} NetworkCommand;

typedef enum {
  NETWORK_PROPERTY_NULL,
  NETWORK_PROPERTY_DISPLAY,
  NETWORK_PROPERTY_CLUSTER_HEAD,
  NETWORK_PROPERTY_ACTIVE_ROUTING,
  NETWORK_PROPERTY_DEBUG_DISPLAY,
  NETWORK_PROPERTY_TEMPORARY_CONNECTION,
  NETWORK_PROPERTY_APP_START = 0x1000,
  NETWORK_PROPERTY_APP_LED_CHAIN,
  NETWORK_PROPERTY_APP_SEND_TXPOWER,
  NETWORK_PROPERTY_APP_AGGERATE_RANGES,
  NETWORK_PROPERTY_APP_SENSIRION,
  NETWORK_PROPERTY_APP_ACCELEROMETER,
  NETWORK_PROPERTY_APP_STREAMING_ACCEL,
  NETWORK_PROPERTY_APP_CAMERA,
  NETWORK_PROPERTY_APP_BOSTON_WATER,
} NetworkProperty;

