COMPONENT=EavesdropperC

# This assumes your State and Transceiver components are in /tos/lib relative to this
# directory:

CFLAGS += -I../../tos/lib/State -I../../tos/lib/Transceiver

#CFLAGS += -DMAX_TOS_MSGS=24

include $(TOSROOT)/apps/Makerules

