COMPONENT=CameraC
#USER_INCLUDES=-I../ptzcamera -I../PEGSensor -I../croute -I../routetest2 -I../position
USER_INCLUDES=-I../PEGSensor -I../croute -I../routetest2 -I../position -I../DiagMsg
SENSORBOARDS=micasb
include ../Makerules

