#COMPONENT=GreedyApp
COMPONENT=DIMApp
SENSORBOARD=micasb
PFLAGS=-I/home/xinl/tinyos-1.x/tos/lib/Attributes -I/home/xinl/tinyos-1.x/tos/lib/Util -I/home/xinl/tinyos-1.x/tos/lib/FS
MSG_SIZE=49
PFLAGS := -DUSEGTS $(PFLAGS)
include ../Makerules
