# Top-level Makefile for tools/java

# We do all subdirectories (to allow for optional package installation)
SUBDIRS = net de

TOS = $(shell ncc -print-tosdir)
ROOT = $(TOS)/../tools/java
include $(ROOT)/Makefile.include
