includes Bombilla;
includes AbstractConstants;

configuration AbstractMate {}
implementation
{
	components BombillaEngine as VM, Main, BContextSynchProxy;
	components OPadd;
	components OPsub;
	components OPhalt;
	components OPland;
	components OPlor;
	components OPor;
	components OPand;
	components OPnot;
	components OPlnot;
	components OPdiv;
	components OPbtail;
	components OPeqv;
	components OPexp;
	components OPimp;
	components OPlxor;
	components OPmod;
	components OPmul;
	components OPbread;
	components OPbwrite;
	components OPpop;
	components OPeq;
	components OPgte;
	components OPgt;
	components OPlt;
	components OPlte;
	components OPneq;
	components OPcopy;
	components OPinv;
	components OPputled;
	components OPbclear;
	components OPcast;
	components OPid;
	components OPuart;
	components OPrand;
	components OProute;
	components OPbpush1;
	components OPsettimer1;
	components OP2pushc10;
	components OP2jumps10;
	components OPgetlocal3;
	components OPsetlocal3;
	components OPgetvar4;
	components OPsetvar4;
	components OPpushc6;
	components Timer1Context;
	components OnceContext;

	Main.StdControl -> VM;
	VM.Bytecode[OPadd+0] -> OPadd;
	VM.Bytecode[OPsub+0] -> OPsub;
	VM.Bytecode[OPhalt+0] -> OPhalt;
	VM.Bytecode[OPland+0] -> OPland;
	VM.Bytecode[OPlor+0] -> OPlor;
	VM.Bytecode[OPor+0] -> OPor;
	VM.Bytecode[OPand+0] -> OPand;
	VM.Bytecode[OPnot+0] -> OPnot;
	VM.Bytecode[OPlnot+0] -> OPlnot;
	VM.Bytecode[OPdiv+0] -> OPdiv;
	VM.Bytecode[OPbtail+0] -> OPbtail;
	VM.Bytecode[OPeqv+0] -> OPeqv;
	VM.Bytecode[OPexp+0] -> OPexp;
	VM.Bytecode[OPimp+0] -> OPimp;
	VM.Bytecode[OPlxor+0] -> OPlxor;
	VM.Bytecode[OPmod+0] -> OPmod;
	VM.Bytecode[OPmul+0] -> OPmul;
	VM.Bytecode[OPbread+0] -> OPbread;
	VM.Bytecode[OPbwrite+0] -> OPbwrite;
	VM.Bytecode[OPpop+0] -> OPpop;
	VM.Bytecode[OPeq+0] -> OPeq;
	VM.Bytecode[OPgte+0] -> OPgte;
	VM.Bytecode[OPgt+0] -> OPgt;
	VM.Bytecode[OPlt+0] -> OPlt;
	VM.Bytecode[OPlte+0] -> OPlte;
	VM.Bytecode[OPneq+0] -> OPneq;
	VM.Bytecode[OPcopy+0] -> OPcopy;
	VM.Bytecode[OPinv+0] -> OPinv;
	VM.Bytecode[OPputled+0] -> OPputled;
	VM.Bytecode[OPbclear+0] -> OPbclear;
	VM.Bytecode[OPcast+0] -> OPcast;
	VM.Bytecode[OPid+0] -> OPid;
	VM.Bytecode[OPuart+0] -> OPuart;
	VM.Bytecode[OPrand+0] -> OPrand;
	VM.Bytecode[OProute+0] -> OProute;

	VM.Bytecode[OPbpush1+0] -> OPbpush1;
	VM.Bytecode[OPbpush1+1] -> OPbpush1;
	VM.Bytecode[OPsettimer1+0] -> OPsettimer1;
	VM.Bytecode[OPsettimer1+1] -> OPsettimer1;

	VM.Bytecode[OP2pushc10+0] -> OP2pushc10;
	VM.Bytecode[OP2pushc10+1] -> OP2pushc10;
	VM.Bytecode[OP2pushc10+2] -> OP2pushc10;
	VM.Bytecode[OP2pushc10+3] -> OP2pushc10;
	VM.Bytecode[OP2jumps10+0] -> OP2jumps10;
	VM.Bytecode[OP2jumps10+1] -> OP2jumps10;
	VM.Bytecode[OP2jumps10+2] -> OP2jumps10;
	VM.Bytecode[OP2jumps10+3] -> OP2jumps10;

	VM.Bytecode[OPgetlocal3+0] -> OPgetlocal3;
	VM.Bytecode[OPgetlocal3+1] -> OPgetlocal3;
	VM.Bytecode[OPgetlocal3+2] -> OPgetlocal3;
	VM.Bytecode[OPgetlocal3+3] -> OPgetlocal3;
	VM.Bytecode[OPgetlocal3+4] -> OPgetlocal3;
	VM.Bytecode[OPgetlocal3+5] -> OPgetlocal3;
	VM.Bytecode[OPgetlocal3+6] -> OPgetlocal3;
	VM.Bytecode[OPgetlocal3+7] -> OPgetlocal3;
	VM.Bytecode[OPsetlocal3+0] -> OPsetlocal3;
	VM.Bytecode[OPsetlocal3+1] -> OPsetlocal3;
	VM.Bytecode[OPsetlocal3+2] -> OPsetlocal3;
	VM.Bytecode[OPsetlocal3+3] -> OPsetlocal3;
	VM.Bytecode[OPsetlocal3+4] -> OPsetlocal3;
	VM.Bytecode[OPsetlocal3+5] -> OPsetlocal3;
	VM.Bytecode[OPsetlocal3+6] -> OPsetlocal3;
	VM.Bytecode[OPsetlocal3+7] -> OPsetlocal3;

	VM.Bytecode[OPgetvar4+0] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+1] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+2] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+3] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+4] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+5] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+6] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+7] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+8] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+9] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+10] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+11] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+12] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+13] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+14] -> OPgetvar4;
	VM.Bytecode[OPgetvar4+15] -> OPgetvar4;
	VM.Bytecode[OPsetvar4+0] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+1] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+2] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+3] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+4] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+5] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+6] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+7] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+8] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+9] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+10] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+11] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+12] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+13] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+14] -> OPsetvar4;
	VM.Bytecode[OPsetvar4+15] -> OPsetvar4;

	VM.Bytecode[OPpushc6+0] -> OPpushc6;
	VM.Bytecode[OPpushc6+1] -> OPpushc6;
	VM.Bytecode[OPpushc6+2] -> OPpushc6;
	VM.Bytecode[OPpushc6+3] -> OPpushc6;
	VM.Bytecode[OPpushc6+4] -> OPpushc6;
	VM.Bytecode[OPpushc6+5] -> OPpushc6;
	VM.Bytecode[OPpushc6+6] -> OPpushc6;
	VM.Bytecode[OPpushc6+7] -> OPpushc6;
	VM.Bytecode[OPpushc6+8] -> OPpushc6;
	VM.Bytecode[OPpushc6+9] -> OPpushc6;
	VM.Bytecode[OPpushc6+10] -> OPpushc6;
	VM.Bytecode[OPpushc6+11] -> OPpushc6;
	VM.Bytecode[OPpushc6+12] -> OPpushc6;
	VM.Bytecode[OPpushc6+13] -> OPpushc6;
	VM.Bytecode[OPpushc6+14] -> OPpushc6;
	VM.Bytecode[OPpushc6+15] -> OPpushc6;
	VM.Bytecode[OPpushc6+16] -> OPpushc6;
	VM.Bytecode[OPpushc6+17] -> OPpushc6;
	VM.Bytecode[OPpushc6+18] -> OPpushc6;
	VM.Bytecode[OPpushc6+19] -> OPpushc6;
	VM.Bytecode[OPpushc6+20] -> OPpushc6;
	VM.Bytecode[OPpushc6+21] -> OPpushc6;
	VM.Bytecode[OPpushc6+22] -> OPpushc6;
	VM.Bytecode[OPpushc6+23] -> OPpushc6;
	VM.Bytecode[OPpushc6+24] -> OPpushc6;
	VM.Bytecode[OPpushc6+25] -> OPpushc6;
	VM.Bytecode[OPpushc6+26] -> OPpushc6;
	VM.Bytecode[OPpushc6+27] -> OPpushc6;
	VM.Bytecode[OPpushc6+28] -> OPpushc6;
	VM.Bytecode[OPpushc6+29] -> OPpushc6;
	VM.Bytecode[OPpushc6+30] -> OPpushc6;
	VM.Bytecode[OPpushc6+31] -> OPpushc6;
	VM.Bytecode[OPpushc6+32] -> OPpushc6;
	VM.Bytecode[OPpushc6+33] -> OPpushc6;
	VM.Bytecode[OPpushc6+34] -> OPpushc6;
	VM.Bytecode[OPpushc6+35] -> OPpushc6;
	VM.Bytecode[OPpushc6+36] -> OPpushc6;
	VM.Bytecode[OPpushc6+37] -> OPpushc6;
	VM.Bytecode[OPpushc6+38] -> OPpushc6;
	VM.Bytecode[OPpushc6+39] -> OPpushc6;
	VM.Bytecode[OPpushc6+40] -> OPpushc6;
	VM.Bytecode[OPpushc6+41] -> OPpushc6;
	VM.Bytecode[OPpushc6+42] -> OPpushc6;
	VM.Bytecode[OPpushc6+43] -> OPpushc6;
	VM.Bytecode[OPpushc6+44] -> OPpushc6;
	VM.Bytecode[OPpushc6+45] -> OPpushc6;
	VM.Bytecode[OPpushc6+46] -> OPpushc6;
	VM.Bytecode[OPpushc6+47] -> OPpushc6;
	VM.Bytecode[OPpushc6+48] -> OPpushc6;
	VM.Bytecode[OPpushc6+49] -> OPpushc6;
	VM.Bytecode[OPpushc6+50] -> OPpushc6;
	VM.Bytecode[OPpushc6+51] -> OPpushc6;
	VM.Bytecode[OPpushc6+52] -> OPpushc6;
	VM.Bytecode[OPpushc6+53] -> OPpushc6;
	VM.Bytecode[OPpushc6+54] -> OPpushc6;
	VM.Bytecode[OPpushc6+55] -> OPpushc6;
	VM.Bytecode[OPpushc6+56] -> OPpushc6;
	VM.Bytecode[OPpushc6+57] -> OPpushc6;
	VM.Bytecode[OPpushc6+58] -> OPpushc6;
	VM.Bytecode[OPpushc6+59] -> OPpushc6;
	VM.Bytecode[OPpushc6+60] -> OPpushc6;
	VM.Bytecode[OPpushc6+61] -> OPpushc6;
	VM.Bytecode[OPpushc6+62] -> OPpushc6;
	VM.Bytecode[OPpushc6+63] -> OPpushc6;


	BContextSynchProxy.CodeLocks[OPbpush1+0] -> OPbpush1;
	BContextSynchProxy.CodeLocks[OPbpush1+1] -> OPbpush1;



	BContextSynchProxy.CodeLocks[OPgetvar4+0] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+1] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+2] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+3] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+4] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+5] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+6] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+7] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+8] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+9] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+10] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+11] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+12] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+13] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+14] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPgetvar4+15] -> OPgetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+0] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+1] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+2] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+3] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+4] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+5] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+6] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+7] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+8] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+9] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+10] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+11] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+12] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+13] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+14] -> OPsetvar4;
	BContextSynchProxy.CodeLocks[OPsetvar4+15] -> OPsetvar4;


}
