COMPONENT = MarkSeq

# Keep on Different Channel and Group from Deployed Network
# which is on Group 0x0a, Channel 0x11
CC2420_CHANNEL := 0x0b
DEFAULT_LOCAL_GROUP := 0x23

include $(TOSDIR)/../apps/Makerules
