#!/bin/sh
#
# This is called by the InstallScript Wizard. The Wizard
# determines, sets, and exports the value of $TOSROOT before
# this is called.
# 

cd $TOSROOT/tools/uisp/kernel/win32
$TOSROOT/tools/uisp/kernel/win32/giveio-install --install

