/*									tab:4
 *  temp_test.h - simple application to test the temperture sensor
 *
 * "Copyright (c) 2002 and The Regents of the University 
 * of California.  All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice and the following
 * two paragraphs appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF
 * CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
 *
 * Authors:  Alec Woo
 * Date:     Jan. 23, 2002
 *
 * This application simply blinks the leds with each clock interrupt, 
 * samples the temperature sensor, and outputs the 8 bit value 
 * over the UART. 
 *
 */

TOS_MODULE TEMP_TEST;

ACCEPTS{
	char TEMP_TEST_INIT(void);
	char TEMP_TEST_START(void);
};

HANDLES{
	void TEMP_TEST_CLOCK_EVENT(void);
	char TEMP_TEST_UART_TX_READY_EVENT(char success);
	char TEMP_TEST_DATA_EVENT(short data);
	char TEMP_TEST_UART_RX_READY_EVENT(char data, char error);
};

USES{
	char TEMP_TEST_SUB_INIT(char interval, char scale);
        char TEMP_TEST_SEND_BYTE(char data);
	char TEMP_TEST_GET_DATA(void);
	char TEMP_TEST_UART_INIT();
	char TEMP_TEST_TEMP_INIT();
        char TEMP_TEST_LEDy_on();
        char TEMP_TEST_LEDy_off();
        char TEMP_TEST_LEDr_on();
        char TEMP_TEST_LEDr_off();
        char TEMP_TEST_LEDg_on();
        char TEMP_TEST_LEDg_off();
};

SIGNALS{
};

