/*									tab:4
 *
 *
 * "Copyright (c) 2000 and The Regents of the University 
 * of California.  All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice and the following
 * two paragraphs appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF
 * CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
 *
 * Authors:		Joe Polastre
 *
 */

TOS_MODULE ROUTER_TEST;


ACCEPTS{
	char ROUTER_TEST_INIT(void);
	char ROUTER_TEST_START(void);
};

HANDLES{
	void ROUTER_TEST_SUB_CLOCK(void);
};

USES{
        char ROUTE_SEND_PACKET(char* data);
	char ROUTER_TEST_SUB_INIT();
	char ROUTER_TEST_SUB_CLOCK_INIT(char interval, char scale);
	char ROUTER_TEST_LED1_OFF();
	char ROUTER_TEST_LED1_ON();
	char ROUTER_TEST_LED1_TOGGLE();
	char ROUTER_TEST_LED2_OFF();
	char ROUTER_TEST_LED2_ON();
	char ROUTER_TEST_LED2_TOGGLE();
	char ROUTER_TEST_LED3_OFF();
	char ROUTER_TEST_LED3_ON();
	char ROUTER_TEST_LED3_TOGGLE();
	char ROUTER_TEST_SUB_LED_INIT();
};

