COMPONENT=../Format/BlackbookFormatC
CFLAGS += -I../Format
CFLAGS += -I../../../../tos/lib/State -I../../interfaces

# If you are using Boomerang, uncomment the following line:
#CFLAGS += -DSTM25P_BOOMERANG_VERSION

include $(MAKERULES)
