COMPONENT=TestYao
#SENSORBOARD = basicsb
SENSORBOARD = micasb
#PFLAGS = -I/opt/avrgcc/avr/include
PFLAGS = -I/usr/include -I../../lib \
  -I../../../../tossim \
  -I../../../lib/fiber \
  -I../../../lib/neighborhood \
  -I../../../lib/location \
  -I../../../lib/network \
  -I../../../lib/sharedvar
include Makerules

