COMPONENT=Surge
#SENSORBOARD=basicsb
SENSORBOARD=micasb

#PFLAGS= -I%T/CC1000RadioAck  -I../../../../beta/CC1000RadioAck -I../../tos/lib/ReliableRoute -I%T/lib/Queue -I%T/lib/Broadcast
#PFLAGS= -I../../../../beta/CC1000RadioAck 
# 

PFLAGS= -I ../../tos/system -I ../../tos/interfaces -I../../../../beta/CC1000RadioAck -I../../tos/lib/ReliableRoute_TimeSync -I%T/lib/Queue -I%T/lib/Broadcast

include ../../../../apps/Makerules
