include ../Makelocal
FIREBOARD_PATH += -I$(MTS420CA)/sensors/adxl202je
LOCAL_PATH += $(FIREBOARD_PATH)

COMPONENT=testadxl

PFLAGS := $(LOCAL_PATH) $(LOCAL_DEFINES) $(PFLAGS)

include $(TOSROOT)/apps/Makerules

