# maximum number of nodes. Should have IDs from 0..MAX_NODES-1
MAX_NODES=2

PFLAGS += -Os -DMAX_NODES=$(MAX_NODES)
PFLAGS += -DDEFAULT_LOCAL_GROUP=0x7f

# disable to remove debug code
PFLAGS += -DTMAC_DEBUG

COMPONENT=Chirp
include ../Makerules


