PFLAGS += -I%T/lib/DiagMsg -I%T/lib/PeaceKeeper -I%T/lib/AcousticRanging
PFLAGS += -I%T/lib/OrderCorrectADC -I%T/lib/RemoteControl -I%T/lib/FloodRouting -I%T/lib/TimeSlotNegotiation
COMPONENT=AcousticLocalizationC
include ../Makerules
