/*									tab:4
 *
 *
 * "Copyright (c) 2000 and The Regents of the University 
 * of California.  All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice and the following
 * two paragraphs appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF
 * CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
 *
 * Authors:		Phil Levis <pal@cs.berkeley.edu>
 *
 * This component implements a simple ping utility for TinyOS. When a mote
 * receives a PING message, it immediately responds with an echo ping.
 * This can be used to check for communication ability, symmetry of links,
 * and packet reliability.
 */     

TOS_MODULE PING_TEST;

ACCEPTS{
	char PING_TEST_INIT();
	char PING_TEST_START();
};

HANDLES{
	char PING_TEST_RECEIVE(short moteID, char sequence);
	void PING_TEST_CLOCK();
};

USES{
	char PING_TEST_SUB_SEND(short moteID, char sequence);
	char PING_TEST_SUB_CLOCK_INIT(char scale, char interval);	
	char PING_TEST_SUB_INIT();
	char PING_TEST_SUB_START();
	char PING_TEST_RED_TOGGLE();
	char PING_TEST_GREEN_TOGGLE();
};

