enum {
  DETECTION_LOG_STATE_IDLE = 0,
  DETECTION_LOG_STATE_ERASE = 1,
  DETECTION_LOG_STATE_SAMPLE = 2,
  DETECTION_LOG_STATE_SYNC = 3,
  DETECTION_LOG_STATE_READ = 4,
  DETECTION_FLASH_ID = 0x0D,
};

