TOSDIR=/home/Neil/tinyos-1.x/tos
COMPONENT=AbstractMateReceiver
CFLAGS=-I../../../types -I../../../interfaces -I../../../components -I../../../opcodes -I../../../contexts
MSG_SIZE=36
include $(TOSDIR)/../apps/Makerules

