#!/usr/bin/perl
#
# "Copyright (c) 2000-2003 The Regents of the University  of California.  
# All rights reserved.
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose, without fee, and without written agreement is
# hereby granted, provided that the above copyright notice, the following
# two paragraphs and the author appear in all copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
# DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
# OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF
# CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
# ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
# PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
#
# Copyright (c) 2002-2003 Intel Corporation
# All rights reserved.
#
# This file is distributed under the terms in the attached INTEL-LICENSE     
# file. If you do not find these files, copies can be found by writing to
# Intel Research Berkeley, 2150 Shattuck Avenue, Suite 1300, Berkeley, CA, 
# 94704.  Attention:  Intel License Inquiry.
#

$base = $0;
$base =~ s/\/javapath$//;
$base = `cd $base;pwd;`;
chop $base;

opendir JARS, "$base/jars";
@add = grep(-f "$_" && /\.jar$/, map "$base/jars/$_", readdir JARS);
closedir JARS;

unshift @add, $base;
unshift @add, ".";

$sys = `uname`;
if ($sys =~ /^CYGWIN/) {
    @add = map { $f = `cygpath -w $_`; chop $f; $f; } @add;
    $sep = ";";
}
else {
    $sep = ":";
}

$oldpath = $ENV{"CLASSPATH"};
$addpath = join($sep, @add);

if ($oldpath) {
    if ($sys =~ /^CYGWIN/) {
	print "$addpath;$oldpath\n";
    } 
    else {
	print "$addpath:$oldpath\n";
    }
}
else {
    print "$addpath\n";
}

