/*									tab{4
 *  TEST_PROG.comp
 *
 * "Copyright (c) 2000 and The Regents of the University 
 * of California.  All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice and the following
 * two paragraphs appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF
 * CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
 *
 * Authors:  Joe Polastre
 *
 */

TOS_MODULE TEST_MICA_WB;
JOINTLY IMPLEMENTED_BY TEST_MICA_WB;

ACCEPTS{
	char TEST_MICA_WB_INIT(void);
	char TEST_MICA_WB_START(void);
};

HANDLES{
	void TEST_MICA_WB_CLOCK_EVENT(void);
	char TEST_MICA_WB_COMM_MSG_SEND_DONE(TOS_MsgPtr data);
	char TEST_MICA_WB_PHOTO_GET_READING_DONE(char sensor, short value);
	char TEST_MICA_WB_SET_SWITCH_ALL_DONE(char success);
	TOS_MsgPtr DATA_MSG(TOS_MsgPtr data);
};
USES{
    	char TEST_MICA_WB_CLOCK_INIT(char data, char scale);
	char TEST_MICA_WB_COMM_SUB_INIT(void);
	char TEST_MICA_WB_COMM_POWER(char mode);
	char TEST_MICA_WB_COMM_SEND_MSG(short addr, char type, TOS_MsgPtr data);
	char TEST_MICA_WB_PHOTO_INIT(void);
	char TEST_MICA_WB_PHOTO_GET_READING(char sensor);
	char TEST_MICA_WB_SET_SWITCH_ALL(char value);
	char YELLOW_LED_TOGGLE(void);
	char RED_LED_TOGGLE(void);
	char GREEN_LED_TOGGLE(void);
};

