COMPONENT=CameraPointer
PFLAGS=-I. -I../common -I../ptzcamera -I../routing -I../localization -I../neighborhood -I../Config -I../commandInterpreter -I../TimedLeds -topdir=`pwd`/..
SENSORBOARDS=basicsb
include ../Makerules

