# Makefile for TestSMAC application. 

# Note the use of ENVIRONMENT=SimpleMac to get the make system to
# include the SMAC library. Remove this if you do not wish to include
# SMAC library. You will not be able to compile this app, then.

COMPONENT=TestSMAC
ENVIRONMENT=SimpleMac
include ../Makerules

