COMPONENT=TestAssert

PFLAGS += -I$(NCUNIT_ROOT)/mote

#uncomment for debug output with support for floating point numbers
#PFLAGS += -Wl,-u,vfprintf -lprintf_flt -lm

GOALS += ncunit
TOSMAKE_PATH += $(NCUNIT_ROOT)/scripts


include $(TOSROOT)/apps/Makerules
