COMPONENT=TestSundial
CFLAGS=-I../../interfaces -I../../neural -I../../../../tos/lib/TinyDB -I../../../../tos/lib/Commands -I../../../../tos/lib/Attributes
include ../../../../tinyos-1.x/apps/Makerules

