COMPONENT=TestFiber
#SENSORBOARD = basicsb
SENSORBOARD = micasb
#PFLAGS = -I/opt/avrgcc/avr/include
PFLAGS = -I/usr/include -I../../ncs/lib \
  -I../../../../collective/neighborhood \
  -I../../../../collective/location \
  -I../../../../collective/network \
  -I../../../../collective/sharedvar

include Makerules

