# $Id: Makefile,v 1.14 2005/02/17 08:56:09 mturon Exp $

include Makefile.component
include ../../MakeXbowlocal

# Automatically add certain command-line goals:
GOALS += mesh freq
TOSMAKE_PATH = ${TOSROOT}/contrib/xbow/tools/make
include ${TOSROOT}/tools/make/Makerules
