COMPONENT=GoldenImage
PFLAGS += -DDELUGE_GOLDEN_IMAGE -DDELUGE_LEDS
CFLAGS += -DTOSH_MAX_TASKS_LOG2=7

TOSMAKE_PATH += $(TOSDIR)/../contrib/nucleus/scripts

PFLAGS += -I$(TOSDIR)/../beta/Drip
PFLAGS += -I$(TOSDIR)/../beta/Drain
PFLAGS += -I$(TOSDIR)/../contrib/nucleus/tos/lib/Nucleus
PFLAGS += -I$(TOSDIR)/../contrib/nucleus/tos/lib/NucleusExamples

include $(TOSDIR)/../apps/Makerules