/**
 * @author Mike Grimmer
 */

enum {
  TOSH_ACTUAL_PHOTO_PORT = 7,
  TOSH_ACTUAL_MIC_PORT = 2, 
  TOSH_ACTUAL_ACCEL_X_PORT = 3, 
  TOSH_ACTUAL_ACCEL_Y_PORT = 4, 
};

enum {
  TOS_ADC_PHOTO_PORT = 7,
  TOS_ADC_MIC_PORT = 2,
  TOS_ADC_ACCEL_X_PORT = 3,
  TOS_ADC_ACCEL_Y_PORT = 4,
};

enum {
  TOS_MAG_POT_ADDR = 0,
  TOS_MIC_POT_ADDR = 1
};

TOSH_ALIAS_PIN(PHOTO_CTL, PW0);
TOSH_ALIAS_PIN(ACCEL_CTL, PW0);
TOSH_ALIAS_OUTPUT_ONLY_PIN(MIC_CTL, PW1);
