enum {
#ifdef CONST_NEIGHBOR_LIST_LEN
   NEIGHBOR_LIST_LEN = CONST_NEIGHBOR_LIST_LEN
#else
   NEIGHBOR_LIST_LEN = 30
#endif
};

enum {
// TODO: make a wise choice or make it settable
   NEIGHBOR_LIST_UPDATE_INTERVAL = 10,
   NEIGHBOR_LIST_NBR_TIMEOUT = 4,
//   NEIGHBOR_HISTORY_INITIAL_VALUE = 0x6db6db6dL,
   NEIGHBOR_HISTORY_INITIAL_VALUE = 0x11111111L,
   NEIGHBOR_HISTORY_PENALTY = 4,
   NEIGHBOR_ACTIVITY_REMOVE_THRESH = 12,
   NEIGHBOR_ACTIVITY_JOIN_THRESH = 6,
   NUM_QUALITY_LEVELS = 4,
   NUM_QUALITY_THOLDS = NUM_QUALITY_LEVELS-1
};

typedef uint32_t HistoryBits_t;
enum{
   NUM_HISTORY_BITS = (sizeof(HistoryBits_t)<<3)
};

enum {
   NEIGHBOR_QUALITY_THOLD0 = 29,
   NEIGHBOR_QUALITY_THOLD1 = 26,
   NEIGHBOR_QUALITY_THOLD2 = 15
};
