#!/bin/sh

i=0
built=0

for ((i=0;;i++)); do

   echo ""
   echo "Insert node $i"
   read a

   if [ "$a" != "" ]; then
      i=$a;
      built=0
   fi

   case $i in
      0)
         echo "make mica install.0 SINK_NODE=1 $*"
         make mica install.0 SINK_NODE=1 $*
         ;;
      *)
         if [ $built -eq 0 ]; then
            echo "make mica install.$i $*"
            make mica install.$i $*
            built=1
         else
            echo "make mica reinstall.$i $*"
            make mica reinstall.$i $*
         fi
         ;;
   esac

done
