COMPONENT=PSDemo
# CFLAGS += -v
CFLAGS += -DTOSH_MAX_TASKS_LOG2=8

PFLAGS += -I%T/../contrib/eyes/tos/lib/PublishSubscribe -I%T/../contrib/eyes/tos/lib/PublishSubscribe/attributes -I%T/../contrib/eyes/tos/lib/PublishSubscribe/servicediscovery -I%T/../contrib/eyes/tos/lib/PublishSubscribe/filters -I%T/../contrib/eyes/tos/lib/TinyAllocMultiple -I%T/lib/Drip/ -I%T/lib/Drain/ -I%T/../contrib/eyes/tos/lib/Broadcast -I%T/../contrib/eyes/tos/lib/MultiHopRSSI -I$(TOSDIR)/../contrib/eyes/tos/lib/LPLMacs -I$(TOSDIR)/../contrib/eyes/tos/lib/Clock


# -I%T/../contrib/eyes/tos/lib/Chips/Pots/AD6200

include ../MakeEyes

