COMPONENT=RandomGenDemoC

# Choose an internal microcontroller flash type
CFLAGS += -I../../../../../tos/lib/FlashBridge/media/msp430
#CFLAGS += -I../../../../../tos/lib/FlashBridge/media/avr
#CFLAGS += -I../../../../../tos/lib/FlashBridge/media/at45db

# RandomGen directories
CFLAGS += -I../../interfaces
CFLAGS += -I../../core

# Configuration directories
CFLAGS += -I../../../../../tos/lib/Configuration/interfaces
CFLAGS += -I../../../../../tos/lib/Configuration/core

# Other Flash directories
CFLAGS += -I../../../../../tos/lib/FlashBridge/interfaces
CFLAGS += -I../../../../../tos/lib/FlashBridge/apps/FlashBridgeViewer

# Utility directories
CFLAGS += -I../../../../../tos/lib/State
CFLAGS += -I../../../../../tos/lib/GenericCrc
CFLAGS += -I../../../../../tos/lib/Transceiver
CFLAGS += -I../../../../../tos/lib/Leds


include $(MAKERULES)

 
