# $Id: Makefile,v 1.7 2005/02/19 01:14:11 mturon Exp $

include Makefile.component
include ../../MakeXbowlocal

# Automatically add certain command-line goals:
GOALS += mesh freq
TOSMAKE_PATH = ${TOSROOT}/contrib/xbow/tools/make
include ${TOSROOT}/tools/make/Makerules
