#define PHOTO_PORT 1 /* TOS_ADC_PORT_1 */ 
#define TEMP_PORT  1 /* TOS_ADC_PORT_2 */ 
#define MIC_PORT   2 /* TOS_ADC_PORT_3 */ 
#define ACCEL_X    3 /* TOS_ADC_PORT_4 */ 
#define ACCEL_Y    4 /* TOS_ADC_PORT_5 */ 
#define MAG_X      6 /* TOS_ADC_PORT_6 */ 
#define MAG_Y      5 /* TOS_ADC_PORT_8 */ 

ALIAS_PIN(PHOTO_CTL, INT1);
ALIAS_PIN(TEMP_CTL, INT2);
ALIAS_PIN(TONE_DECODE_SIGNAL, INT3);
ALIAS_OUTPUT_ONLY_PIN(MIC_CTL, PW3);
ALIAS_OUTPUT_ONLY_PIN(SOUNDER_CTL, PW2);
ALIAS_OUTPUT_ONLY_PIN(ACCEL_CTL, PW4);
ALIAS_OUTPUT_ONLY_PIN(MAG_CTL, PW5);
ALIAS_OUTPUT_ONLY_PIN(MIC_MUX_SEL, PW6);

#define MIC_POT_ADDR  1
#define MAG_POT_ADDR  0


