/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'BVRBeaconMessage'
 * message type.
 */

package net.tinyos.bvr.messages;

public class BVRBeaconMessage extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 30;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 56;

    /** Create a new BVRBeaconMessage of size 30. */
    public BVRBeaconMessage() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new BVRBeaconMessage of the given data_length. */
    public BVRBeaconMessage(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BVRBeaconMessage with the given data_length
     * and base offset.
     */
    public BVRBeaconMessage(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BVRBeaconMessage using the given byte array
     * as backing store.
     */
    public BVRBeaconMessage(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BVRBeaconMessage using the given byte array
     * as backing store, with the given base offset.
     */
    public BVRBeaconMessage(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BVRBeaconMessage using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public BVRBeaconMessage(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BVRBeaconMessage embedded in the given message
     * at the given base offset.
     */
    public BVRBeaconMessage(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BVRBeaconMessage embedded in the given message
     * at the given base offset and length.
     */
    public BVRBeaconMessage(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <BVRBeaconMessage> \n";
      try {
        s += "  [header.last_hop=0x"+Long.toHexString(get_header_last_hop())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [header.seqno=0x"+Long.toHexString(get_header_seqno())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [type_data.seqno=0x"+Long.toHexString(get_type_data_seqno())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [type_data.beacons.hopcount=";
        for (int i = 0; i < 8; i++) {
          s += "0x"+Long.toHexString(getElement_type_data_beacons_hopcount(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [type_data.beacons.seqno=";
        for (int i = 0; i < 8; i++) {
          s += "0x"+Long.toHexString(getElement_type_data_beacons_seqno(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [type_data.beacons.quality=";
        for (int i = 0; i < 8; i++) {
          s += "0x"+Long.toHexString(getElement_type_data_beacons_quality(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: header.last_hop
    //   Field type: int
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'header.last_hop' is signed (false).
     */
    public static boolean isSigned_header_last_hop() {
        return false;
    }

    /**
     * Return whether the field 'header.last_hop' is an array (false).
     */
    public static boolean isArray_header_last_hop() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'header.last_hop'
     */
    public static int offset_header_last_hop() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'header.last_hop'
     */
    public static int offsetBits_header_last_hop() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'header.last_hop'
     */
    public int get_header_last_hop() {
        return (int)getUIntElement(offsetBits_header_last_hop(), 16);
    }

    /**
     * Set the value of the field 'header.last_hop'
     */
    public void set_header_last_hop(int value) {
        setUIntElement(offsetBits_header_last_hop(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'header.last_hop'
     */
    public static int size_header_last_hop() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'header.last_hop'
     */
    public static int sizeBits_header_last_hop() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: header.seqno
    //   Field type: int
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'header.seqno' is signed (false).
     */
    public static boolean isSigned_header_seqno() {
        return false;
    }

    /**
     * Return whether the field 'header.seqno' is an array (false).
     */
    public static boolean isArray_header_seqno() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'header.seqno'
     */
    public static int offset_header_seqno() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'header.seqno'
     */
    public static int offsetBits_header_seqno() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'header.seqno'
     */
    public int get_header_seqno() {
        return (int)getUIntElement(offsetBits_header_seqno(), 16);
    }

    /**
     * Set the value of the field 'header.seqno'
     */
    public void set_header_seqno(int value) {
        setUIntElement(offsetBits_header_seqno(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'header.seqno'
     */
    public static int size_header_seqno() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'header.seqno'
     */
    public static int sizeBits_header_seqno() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: type_data.seqno
    //   Field type: int
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'type_data.seqno' is signed (false).
     */
    public static boolean isSigned_type_data_seqno() {
        return false;
    }

    /**
     * Return whether the field 'type_data.seqno' is an array (false).
     */
    public static boolean isArray_type_data_seqno() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'type_data.seqno'
     */
    public static int offset_type_data_seqno() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'type_data.seqno'
     */
    public static int offsetBits_type_data_seqno() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'type_data.seqno'
     */
    public int get_type_data_seqno() {
        return (int)getUIntElement(offsetBits_type_data_seqno(), 16);
    }

    /**
     * Set the value of the field 'type_data.seqno'
     */
    public void set_type_data_seqno(int value) {
        setUIntElement(offsetBits_type_data_seqno(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'type_data.seqno'
     */
    public static int size_type_data_seqno() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'type_data.seqno'
     */
    public static int sizeBits_type_data_seqno() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: type_data.beacons.hopcount
    //   Field type: short[]
    //   Offset (bits): 0
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'type_data.beacons.hopcount' is signed (false).
     */
    public static boolean isSigned_type_data_beacons_hopcount() {
        return false;
    }

    /**
     * Return whether the field 'type_data.beacons.hopcount' is an array (true).
     */
    public static boolean isArray_type_data_beacons_hopcount() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'type_data.beacons.hopcount'
     */
    public static int offset_type_data_beacons_hopcount(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 8) throw new ArrayIndexOutOfBoundsException();
        offset += 48 + index1 * 24;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'type_data.beacons.hopcount'
     */
    public static int offsetBits_type_data_beacons_hopcount(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 8) throw new ArrayIndexOutOfBoundsException();
        offset += 48 + index1 * 24;
        return offset;
    }

    /**
     * Return the entire array 'type_data.beacons.hopcount' as a short[]
     */
    public short[] get_type_data_beacons_hopcount() {
        short[] tmp = new short[8];
        for (int index0 = 0; index0 < numElements_type_data_beacons_hopcount(0); index0++) {
            tmp[index0] = getElement_type_data_beacons_hopcount(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'type_data.beacons.hopcount' from the given short[]
     */
    public void set_type_data_beacons_hopcount(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_type_data_beacons_hopcount(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'type_data.beacons.hopcount'
     */
    public short getElement_type_data_beacons_hopcount(int index1) {
        return (short)getUIntElement(offsetBits_type_data_beacons_hopcount(index1), 8);
    }

    /**
     * Set an element of the array 'type_data.beacons.hopcount'
     */
    public void setElement_type_data_beacons_hopcount(int index1, short value) {
        setUIntElement(offsetBits_type_data_beacons_hopcount(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'type_data.beacons.hopcount'
     */
    public static int totalSize_type_data_beacons_hopcount() {
        return (192 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'type_data.beacons.hopcount'
     */
    public static int totalSizeBits_type_data_beacons_hopcount() {
        return 192;
    }

    /**
     * Return the size, in bytes, of each element of the array 'type_data.beacons.hopcount'
     */
    public static int elementSize_type_data_beacons_hopcount() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'type_data.beacons.hopcount'
     */
    public static int elementSizeBits_type_data_beacons_hopcount() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'type_data.beacons.hopcount'
     */
    public static int numDimensions_type_data_beacons_hopcount() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'type_data.beacons.hopcount'
     */
    public static int numElements_type_data_beacons_hopcount() {
        return 8;
    }

    /**
     * Return the number of elements in the array 'type_data.beacons.hopcount'
     * for the given dimension.
     */
    public static int numElements_type_data_beacons_hopcount(int dimension) {
      int array_dims[] = { 8,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'type_data.beacons.hopcount' with a String
     */
    public void setString_type_data_beacons_hopcount(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_type_data_beacons_hopcount(i, (short)s.charAt(i));
         }
         setElement_type_data_beacons_hopcount(i, (short)0); //null terminate
    }

    /**
     * Read the array 'type_data.beacons.hopcount' as a String
     */
    public String getString_type_data_beacons_hopcount() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,8)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_type_data_beacons_hopcount(i) == (char)0) break;
             carr[i] = (char)getElement_type_data_beacons_hopcount(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: type_data.beacons.seqno
    //   Field type: short[]
    //   Offset (bits): 8
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'type_data.beacons.seqno' is signed (false).
     */
    public static boolean isSigned_type_data_beacons_seqno() {
        return false;
    }

    /**
     * Return whether the field 'type_data.beacons.seqno' is an array (true).
     */
    public static boolean isArray_type_data_beacons_seqno() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'type_data.beacons.seqno'
     */
    public static int offset_type_data_beacons_seqno(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 8) throw new ArrayIndexOutOfBoundsException();
        offset += 48 + index1 * 24;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'type_data.beacons.seqno'
     */
    public static int offsetBits_type_data_beacons_seqno(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 8) throw new ArrayIndexOutOfBoundsException();
        offset += 48 + index1 * 24;
        return offset;
    }

    /**
     * Return the entire array 'type_data.beacons.seqno' as a short[]
     */
    public short[] get_type_data_beacons_seqno() {
        short[] tmp = new short[8];
        for (int index0 = 0; index0 < numElements_type_data_beacons_seqno(0); index0++) {
            tmp[index0] = getElement_type_data_beacons_seqno(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'type_data.beacons.seqno' from the given short[]
     */
    public void set_type_data_beacons_seqno(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_type_data_beacons_seqno(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'type_data.beacons.seqno'
     */
    public short getElement_type_data_beacons_seqno(int index1) {
        return (short)getUIntElement(offsetBits_type_data_beacons_seqno(index1), 8);
    }

    /**
     * Set an element of the array 'type_data.beacons.seqno'
     */
    public void setElement_type_data_beacons_seqno(int index1, short value) {
        setUIntElement(offsetBits_type_data_beacons_seqno(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'type_data.beacons.seqno'
     */
    public static int totalSize_type_data_beacons_seqno() {
        return (192 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'type_data.beacons.seqno'
     */
    public static int totalSizeBits_type_data_beacons_seqno() {
        return 192;
    }

    /**
     * Return the size, in bytes, of each element of the array 'type_data.beacons.seqno'
     */
    public static int elementSize_type_data_beacons_seqno() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'type_data.beacons.seqno'
     */
    public static int elementSizeBits_type_data_beacons_seqno() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'type_data.beacons.seqno'
     */
    public static int numDimensions_type_data_beacons_seqno() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'type_data.beacons.seqno'
     */
    public static int numElements_type_data_beacons_seqno() {
        return 8;
    }

    /**
     * Return the number of elements in the array 'type_data.beacons.seqno'
     * for the given dimension.
     */
    public static int numElements_type_data_beacons_seqno(int dimension) {
      int array_dims[] = { 8,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'type_data.beacons.seqno' with a String
     */
    public void setString_type_data_beacons_seqno(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_type_data_beacons_seqno(i, (short)s.charAt(i));
         }
         setElement_type_data_beacons_seqno(i, (short)0); //null terminate
    }

    /**
     * Read the array 'type_data.beacons.seqno' as a String
     */
    public String getString_type_data_beacons_seqno() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,8)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_type_data_beacons_seqno(i) == (char)0) break;
             carr[i] = (char)getElement_type_data_beacons_seqno(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: type_data.beacons.quality
    //   Field type: short[]
    //   Offset (bits): 16
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'type_data.beacons.quality' is signed (false).
     */
    public static boolean isSigned_type_data_beacons_quality() {
        return false;
    }

    /**
     * Return whether the field 'type_data.beacons.quality' is an array (true).
     */
    public static boolean isArray_type_data_beacons_quality() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'type_data.beacons.quality'
     */
    public static int offset_type_data_beacons_quality(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 8) throw new ArrayIndexOutOfBoundsException();
        offset += 48 + index1 * 24;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'type_data.beacons.quality'
     */
    public static int offsetBits_type_data_beacons_quality(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 8) throw new ArrayIndexOutOfBoundsException();
        offset += 48 + index1 * 24;
        return offset;
    }

    /**
     * Return the entire array 'type_data.beacons.quality' as a short[]
     */
    public short[] get_type_data_beacons_quality() {
        short[] tmp = new short[8];
        for (int index0 = 0; index0 < numElements_type_data_beacons_quality(0); index0++) {
            tmp[index0] = getElement_type_data_beacons_quality(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'type_data.beacons.quality' from the given short[]
     */
    public void set_type_data_beacons_quality(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_type_data_beacons_quality(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'type_data.beacons.quality'
     */
    public short getElement_type_data_beacons_quality(int index1) {
        return (short)getUIntElement(offsetBits_type_data_beacons_quality(index1), 8);
    }

    /**
     * Set an element of the array 'type_data.beacons.quality'
     */
    public void setElement_type_data_beacons_quality(int index1, short value) {
        setUIntElement(offsetBits_type_data_beacons_quality(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'type_data.beacons.quality'
     */
    public static int totalSize_type_data_beacons_quality() {
        return (192 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'type_data.beacons.quality'
     */
    public static int totalSizeBits_type_data_beacons_quality() {
        return 192;
    }

    /**
     * Return the size, in bytes, of each element of the array 'type_data.beacons.quality'
     */
    public static int elementSize_type_data_beacons_quality() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'type_data.beacons.quality'
     */
    public static int elementSizeBits_type_data_beacons_quality() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'type_data.beacons.quality'
     */
    public static int numDimensions_type_data_beacons_quality() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'type_data.beacons.quality'
     */
    public static int numElements_type_data_beacons_quality() {
        return 8;
    }

    /**
     * Return the number of elements in the array 'type_data.beacons.quality'
     * for the given dimension.
     */
    public static int numElements_type_data_beacons_quality(int dimension) {
      int array_dims[] = { 8,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'type_data.beacons.quality' with a String
     */
    public void setString_type_data_beacons_quality(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_type_data_beacons_quality(i, (short)s.charAt(i));
         }
         setElement_type_data_beacons_quality(i, (short)0); //null terminate
    }

    /**
     * Read the array 'type_data.beacons.quality' as a String
     */
    public String getString_type_data_beacons_quality() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,8)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_type_data_beacons_quality(i) == (char)0) break;
             carr[i] = (char)getElement_type_data_beacons_quality(i);
         }
         return new String(carr,0,i);
    }

}
