#SENSORBOARD=micasb
COMPONENT=TelosRssiC
#CFLAGS=-v
#strict-align doesn't work?  why not? -mpm
CFLAGS=-mstrict-align -v
#CFLAGS=-I../../tos/lib/Attributes -I../../tos/lib/Commands -I../../tos/lib/Ranging
#include ../Makerules
include ${MAKERULES}
#PLATFORMS=mica2dot
PLATFORMS = telos telosa telosb
