#For these classes to be used, one must add /contrib/eyes/tools/java to the CLASSPATH
TOS = $(shell ncc -print-tosdir)

PACKAGE = de.tub.eyes.ps #net.tinyos.package
MIG = mig java

ROOT = $(TOS)/../tools/java
include $(ROOT)/Makefile.include


