/** 
 * This class was automatically generated by mig but modified in order
 * to account for dynamic size members of the message struct. This
 * class implements a Java interface to the 'PSNotificationMsg'
 * message type. Modifications done by @author Jan Hauer 
 */

package de.tub.eyes.ps;

public class PSNotificationMsg extends net.tinyos.message.Message {

    /*** Size of header and ps_avpair_t members in bits ***/
    public static final int SIZEOF_HEADER_TYPE = 1 * 8;
    public static final int SIZEOF_HEADER_TOTALLENGTH = 1 * 8;
    public static final int SIZEOF_ATTRIBUTE_ID = 2 * 8;
    public static final int SIZEOF_OPERATION_ID = 1 * 8;
    /*** type constants ***/
    public static final int PS_ITEM_TYPE_CONSTRAINT = 0;
    public static final int PS_ITEM_TYPE_AVPAIR = 1;

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 10;    
    
    /*** offset in bits of data[] in msg */
     public static final int DATA_OFFSET = DEFAULT_MESSAGE_SIZE * 8;


    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 155;

    /** Create a new PSNotificationMsg of size 9. */
    public PSNotificationMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new PSNotificationMsg of the given data_length. */
    public PSNotificationMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PSNotificationMsg with the given data_length
     * and base offset.
     */
    public PSNotificationMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PSNotificationMsg using the given byte array
     * as backing store.
     */
    public PSNotificationMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PSNotificationMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public PSNotificationMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PSNotificationMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public PSNotificationMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PSNotificationMsg embedded in the given message
     * at the given base offset.
     */
    public PSNotificationMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PSNotificationMsg embedded in the given message
     * at the given base offset and length.
     */
    public PSNotificationMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <PSNotificationMsg> \n";
      try {
        s += "  [parentAddress=0x"+Long.toHexString(get_parentAddress())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sourceAddress=0x"+Long.toHexString(get_sourceAddress())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [subscriberID=0x"+Long.toHexString(get_subscriberID())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [subscriptionID=0x"+Long.toHexString(get_subscriptionID())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [flags=0x"+Long.toHexString(get_flags())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [dataLength=0x"+Long.toHexString(get_dataLength())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: parentAddress
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'parentAddress' is signed (false).
     */
    public static boolean isSigned_parentAddress() {
        return false;
    }

    /**
     * Return whether the field 'parentAddress' is an array (false).
     */
    public static boolean isArray_parentAddress() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'parentAddress'
     */
    public static int offset_parentAddress() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'parentAddress'
     */
    public static int offsetBits_parentAddress() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'parentAddress'
     */
    public int get_parentAddress() {
        return (int)getUIntBEElement(offsetBits_parentAddress(), 16);
    }

    /**
     * Set the value of the field 'parentAddress'
     */
    public void set_parentAddress(int value) {
        setUIntBEElement(offsetBits_parentAddress(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'parentAddress'
     */
    public static int size_parentAddress() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'parentAddress'
     */
    public static int sizeBits_parentAddress() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sourceAddress
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sourceAddress' is signed (false).
     */
    public static boolean isSigned_sourceAddress() {
        return false;
    }

    /**
     * Return whether the field 'sourceAddress' is an array (false).
     */
    public static boolean isArray_sourceAddress() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sourceAddress'
     */
    public static int offset_sourceAddress() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sourceAddress'
     */
    public static int offsetBits_sourceAddress() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'sourceAddress'
     */
    public int get_sourceAddress() {
        return (int)getUIntBEElement(offsetBits_sourceAddress(), 16);
    }

    /**
     * Set the value of the field 'sourceAddress'
     */
    public void set_sourceAddress(int value) {
        setUIntBEElement(offsetBits_sourceAddress(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sourceAddress'
     */
    public static int size_sourceAddress() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sourceAddress'
     */
    public static int sizeBits_sourceAddress() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: subscriberID
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'subscriberID' is signed (false).
     */
    public static boolean isSigned_subscriberID() {
        return false;
    }

    /**
     * Return whether the field 'subscriberID' is an array (false).
     */
    public static boolean isArray_subscriberID() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'subscriberID'
     */
    public static int offset_subscriberID() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'subscriberID'
     */
    public static int offsetBits_subscriberID() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'subscriberID'
     */
    public int get_subscriberID() {
        return (int)getUIntBEElement(offsetBits_subscriberID(), 16);
    }

    /**
     * Set the value of the field 'subscriberID'
     */
    public void set_subscriberID(int value) {
        setUIntBEElement(offsetBits_subscriberID(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'subscriberID'
     */
    public static int size_subscriberID() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'subscriberID'
     */
    public static int sizeBits_subscriberID() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: subscriptionID
    //   Field type: short, unsigned
    //   Offset (bits): 48
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'subscriptionID' is signed (false).
     */
    public static boolean isSigned_subscriptionID() {
        return false;
    }

    /**
     * Return whether the field 'subscriptionID' is an array (false).
     */
    public static boolean isArray_subscriptionID() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'subscriptionID'
     */
    public static int offset_subscriptionID() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'subscriptionID'
     */
    public static int offsetBits_subscriptionID() {
        return 48;
    }

    /**
     * Return the value (as a short) of the field 'subscriptionID'
     */
    public short get_subscriptionID() {
        return (short)getUIntBEElement(offsetBits_subscriptionID(), 8);
    }

    /**
     * Set the value of the field 'subscriptionID'
     */
    public void set_subscriptionID(short value) {
        setUIntBEElement(offsetBits_subscriptionID(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'subscriptionID'
     */
    public static int size_subscriptionID() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'subscriptionID'
     */
    public static int sizeBits_subscriptionID() {
        return 8;
    }

    
    /////////////////////////////////////////////////////////
    // Accessor methods for field: modificationCounter
    //   Field type: short, unsigned
    //   Offset (bits): 56
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    public static int offset_modificationCounter() {
        return (56 / 8);
    }
    public static int offsetBits_modificationCounter() {
        return 56;
    }    
    public short get_modificationCounter() {
        return (short)getUIntBEElement(offsetBits_modificationCounter(), 8);
    }
    

    /////////////////////////////////////////////////////////
    // Accessor methods for field: flags
    //   Field type: short, unsigned
    //   Offset (bits): 64
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'flags' is signed (false).
     */
    public static boolean isSigned_flags() {
        return false;
    }

    /**
     * Return whether the field 'flags' is an array (false).
     */
    public static boolean isArray_flags() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'flags'
     */
    public static int offset_flags() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'flags'
     */
    public static int offsetBits_flags() {
        return 64;
    }

    /**
     * Return the value (as a short) of the field 'flags'
     */
    public short get_flags() {
        return (short)getUIntBEElement(offsetBits_flags(), 8);
    }

    /**
     * Set the value of the field 'flags'
     */
    public void set_flags(short value) {
        setUIntBEElement(offsetBits_flags(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'flags'
     */
    public static int size_flags() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'flags'
     */
    public static int sizeBits_flags() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: dataLength
    //   Field type: short, unsigned
    //   Offset (bits): 72
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'dataLength' is signed (false).
     */
    public static boolean isSigned_dataLength() {
        return false;
    }

    /**
     * Return whether the field 'dataLength' is an array (false).
     */
    public static boolean isArray_dataLength() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'dataLength'
     */
    public static int offset_dataLength() {
        return (72 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'dataLength'
     */
    public static int offsetBits_dataLength() {
        return 72;
    }

    /**
     * Return the value (as a short) of the field 'dataLength'
     */
    public short get_dataLength() {
        return (short)getUIntBEElement(offsetBits_dataLength(), 8);
    }

    /**
     * Set the value of the field 'dataLength'
     */
    public void set_dataLength(short value) {
        setUIntBEElement(offsetBits_dataLength(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'dataLength'
     */
    public static int size_dataLength() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'dataLength'
     */
    public static int sizeBits_dataLength() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data
    //   Field type: short[], unsigned
    //   Offset (bits): 80
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data' is signed (false).
     */
    public static boolean isSigned_data() {
        return false;
    }

    /**
     * Return whether the field 'data' is an array (true).
     */
    public static boolean isArray_data() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data'
     */
    public static int offset_data(int index1) {
        int offset = 80;
        if (index1 < 0) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data'
     */
    public static int offsetBits_data(int index1) {
        int offset = 80;
        if (index1 < 0) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'data' as a short[]
     */
    public short[] get_data() {
        throw new IllegalArgumentException("Cannot get field as array - unknown size");
    }

    /**
     * Set the contents of the array 'data' from the given short[]
     */
    public void set_data(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'data'
     */
    public short getElement_data(int index1) {
        return (short)getUIntBEElement(offsetBits_data(index1), 8);
    }

    /**
     * Set an element of the array 'data'
     */
    public void setElement_data(int index1, short value) {
        setUIntBEElement(offsetBits_data(index1), 8, value);
    }

    /**
     * Return the size, in bytes, of each element of the array 'data'
     */
    public static int elementSize_data() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data'
     */
    public static int elementSizeBits_data() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'data'
     */
    public static int numDimensions_data() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data'
     * for the given dimension.
     */
    public static int numElements_data(int dimension) {
      int array_dims[] = { 0,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'data' with a String
     */
    public void setString_data(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_data(i, (short)s.charAt(i));
         }
         setElement_data(i, (short)0); //null terminate
    }

    /**
     * Read the array 'data' as a String
     */
    public String getString_data() { 
         char carr[] = new char[net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_data(i) == (char)0) break;
             carr[i] = (char)getElement_data(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: constraint/avpairs
    // Manually added.
    /////////////////////////////////////////////////////////

    /** 
     *
     * Returns the number of attribute-value pairs in the PSNotificationMsg.
     */
    public int getAVPairCount() 
    { 
     int offset = offsetBits_firstheader();
     int lastBit = offset + get_dataLength() * 8 - 1;
     int count = 0;
     int length;
     
     while (offset < lastBit){
       if (getUIntBEElement(offset, 8) == PS_ITEM_TYPE_AVPAIR)
         count++;
       length = (int) getUIntBEElement(offset + 8, 8) * 8;
       if (length == 0)
         // corrupt data !!!
         return 0;
       offset += length;
     }
     return count;
    }
   
    /** Returns the attribute ID in avpair[index]
     * where: 0 <= index < getAVPairCount()
     *
     * @param index index to avpair[]
     * @exception ArrayIndexOutOfBoundsException for invalid index
     */
    public int getAVPairAttributeID(int index)
    {
     int offset = offsetBits_firstheader();
     int lastBit = offset + get_dataLength() * 8 - 1;
     int count = 0;
      
     while (offset < lastBit){
       if ((int) getUIntBEElement(offset, 8) == PS_ITEM_TYPE_AVPAIR){
         if (count == index)
           break;
         count++;
       }
       offset += (int) getUIntBEElement(offset + SIZEOF_HEADER_TYPE, 8) * 8;
     }
     
     if (offset < lastBit)
       return (int) getUIntBEElement(offset + SIZEOF_HEADER_TYPE +
           SIZEOF_HEADER_TOTALLENGTH, SIZEOF_ATTRIBUTE_ID);
     else
       throw new ArrayIndexOutOfBoundsException("PSNotificationMsg.getAVPairAttributeID: Bad index: "+index+" (should be < "+getAVPairCount()+")");
    }

    /** Returns the value in avpair[index]
     * where: 0 <= index < getAVPairCount()
     *
     * @param index index to avpair[]
     * @exception ArrayIndexOutOfBoundsException for invalid index
     */
    public Short[] getAVPairValue(int index)
    {
     int offset = offsetBits_firstheader();
     int lastBit = offset + get_dataLength() * 8 - 1;
     int count = 0;
     int length;
     Short[] result;
    
     while (offset < lastBit){
       if ((int) getUIntBEElement(offset, 8) == PS_ITEM_TYPE_AVPAIR){
         if (count == index)
           break;
         count++;
       }
       offset += (int) getUIntBEElement(offset + SIZEOF_HEADER_TYPE, 8) * 8;
     }

     if (offset < lastBit){
       length = (int) getUIntBEElement(offset + SIZEOF_HEADER_TYPE, 8) * 8;
       length = length - (SIZEOF_HEADER_TYPE + SIZEOF_HEADER_TOTALLENGTH + SIZEOF_ATTRIBUTE_ID);
       length /= 8;
       result = new Short[length];
       for (int i=0; i<length; i++){
         result[i] = new Short((short) getUIntBEElement(offset + SIZEOF_HEADER_TYPE +
           SIZEOF_HEADER_TOTALLENGTH + SIZEOF_ATTRIBUTE_ID + i*8, 8));
       }
       return result;
     } else {
       throw new ArrayIndexOutOfBoundsException("PSNotificationMsg.getAVPairAttributeID: Bad index: "+index+" (should be < "+getAVPairCount()+")");
     }
    }
    
    /** 
     *
     * Returns the number of requests (=constraints) in the PSNotificationMsg.
     */
    public int getRequestCount() 
    { 
     int offset = offsetBits_firstheader();
     int lastBit = offset + get_dataLength() * 8 - 1;
     int count = 0;
     int length;
     
     while (offset < lastBit){
       if (getUIntBEElement(offset, 8) == PS_ITEM_TYPE_CONSTRAINT)
         count++;
       length = (int) getUIntBEElement(offset + 8, 8) * 8;
       if (length == 0)
         // corrupt data !!!
         return 0;
       offset += length;
     }
     return count;
    }
   
    /** Returns the attribute ID in request[index]
     * where: 0 <= index < getRequestCount()
     *
     * @param index index to request[]
     * @exception ArrayIndexOutOfBoundsException for invalid index
     */
    public int getRequestAttributeID(int index)
    {
     int offset = offsetBits_firstheader();
     int lastBit = offset + get_dataLength() * 8 - 1;
     int count = 0;
      
     while (offset < lastBit){
       if ((int) getUIntBEElement(offset, 8) == PS_ITEM_TYPE_CONSTRAINT){
         if (count == index)
           break;
         count++;
       }
       offset += (int) getUIntBEElement(offset + SIZEOF_HEADER_TYPE, 8) * 8;
     }
     
     if (offset < lastBit)
       return (int) getUIntBEElement(offset + SIZEOF_HEADER_TYPE +
           SIZEOF_HEADER_TOTALLENGTH, SIZEOF_ATTRIBUTE_ID);
     else
       throw new ArrayIndexOutOfBoundsException("PSNotificationMsg.getAVPairAttributeID: Bad index: "+index+" (should be < "+getAVPairCount()+")");
    }

    /** Returns the operation ID in request[index]
     * where: 0 <= index < getRequestCount()
     *
     * @param index index to request[]
     * @exception ArrayIndexOutOfBoundsException for invalid index
     */
    public int getRequestOperationID(int index)
    {
     int offset = offsetBits_firstheader();
     int lastBit = offset + get_dataLength() * 8 - 1;
     int count = 0;
      
     while (offset < lastBit){
       if ((int) getUIntBEElement(offset, 8) == PS_ITEM_TYPE_CONSTRAINT){
         if (count == index)
           break;
         count++;
       }
       offset += (int) getUIntBEElement(offset + SIZEOF_HEADER_TYPE, 8) * 8;
     }
     
     if (offset < lastBit)
       return (int) getUIntBEElement(offset + SIZEOF_HEADER_TYPE +
           SIZEOF_HEADER_TOTALLENGTH + SIZEOF_ATTRIBUTE_ID,
           SIZEOF_OPERATION_ID);
     else
       throw new ArrayIndexOutOfBoundsException("PSNotificationMsg.getAVPairAttributeID: Bad index: "+index+" (should be < "+getAVPairCount()+")");
    }

    /** Returns the value in avpair[index]
     * where: 0 <= index < getAVPairCount()
     *
     * @param index index to avpair[]
     * @exception ArrayIndexOutOfBoundsException for invalid index
     */
    public Short[] getRequestValue(int index)
    {
     int offset = offsetBits_firstheader();
     int lastBit = offset + get_dataLength() * 8 - 1;
     int count = 0;
     int length;
     Short[] result;
    
     while (offset < lastBit){
       if ((int) getUIntBEElement(offset, 8) == PS_ITEM_TYPE_CONSTRAINT){
         if (count == index)
           break;
         count++;
       }
       offset += (int) getUIntBEElement(offset + SIZEOF_HEADER_TYPE, 8) * 8;
     }

     if (offset < lastBit){
       length = (int) getUIntBEElement(offset + SIZEOF_HEADER_TYPE, 8) * 8;
       length = length - (SIZEOF_HEADER_TYPE + SIZEOF_HEADER_TOTALLENGTH + 
           SIZEOF_ATTRIBUTE_ID + SIZEOF_OPERATION_ID);
       length /= 8;
       result = new Short[length];
       for (int i=0; i<length; i++){
         result[i] = new Short((short) getUIntBEElement(offset + SIZEOF_HEADER_TYPE + SIZEOF_HEADER_TOTALLENGTH + SIZEOF_ATTRIBUTE_ID + SIZEOF_OPERATION_ID + i*8, 8));
       }
       return result;
     } else {
       throw new ArrayIndexOutOfBoundsException("PSNotificationMsg.getAVPairAttributeID: Bad index: "+index+" (should be < "+getAVPairCount()+")");
     }
    }
    
    
    /**
     * Return the offset (in bits) of the field PSSubscriptionMsg.data
     */
    public static int offsetBits_firstheader() {
        return DATA_OFFSET;
    }
    
    /**
     * Return the number of bits left in the field PSSubscriptionMsg.data
     * (for constraints and avpair).
     */
    public int getSizeLeftBytes() {
      return (getSizeLeftBits() / 8);
    }
    
    /**
     * Return the number of bits left in the field PSSubscriptionMsg.data
     * (for constraints and avpair).
     */
    public int getSizeLeftBits() {
      int offset = offsetBits_firstheader() + get_dataLength() * 8;
      return (DEFAULT_MESSAGE_SIZE * 8 - offset);
    }
    
    /**
     * Return the current size of the PSSubscriptionMsg in Byte
     */
    public int getTotalMessageSizeBytes() {
        return (getTotalMessageSizeBits() / 8);
    }

    /**
     * Return the current size of the PSSubscriptionMsg in Bits
     */
    public int getTotalMessageSizeBits() {
        int size = offsetBits_firstheader();
        size += get_dataLength() * 8;
        return size;
    }



}
