COMPONENT=../Format/BlackbookFormatC
CFLAGS += -I../../../../tos/lib/State -I../../interfaces

## Choose a flash type:
#CFLAGS += -I../AT45DB
CFLAGS += -I../STM25P

# If you are using Boomerang, uncomment the following line:
#CFLAGS += -DSTM25P_BOOMERANG_VERSION

include $(MAKERULES)
