COMPONENT=FlashBridgeViewerTestC

# Choose a flash type:
#CFLAGS += -I../../media/AT45DB
CFLAGS += -I../../media/STM25P

# Standard include directories:
CFLAGS += -I../../interfaces
CFLAGS += -I../../../../tos/lib/State 

# If you use Boomerang, comment this line out:
CFLAGS += -I../../../../tos/lib/Transceiver

# If you use Boomerang, uncomment these lines out:
#CFLAGS += -DSTM25P_BOOMERANG_VERSION
#CFLAGS += -I../../../../tos/lib/sptransceiver

include $(MAKERULES)


 
