//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by iMoteConsole.rc
//
#define IDI_IMOTE2                      5
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_IMOTECONSOLE_DIALOG         102
#define IDD_IMOTETERMINAL               103
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       130
#define IDD_PP_CONFIGURATION            132
#define IDB_BITMAP_ZOOMIN               132
#define IDB_BITMAP_ZOOMOUT              133
#define IDD_PP_DATAFORMAT               134
#define IDB_BITMAP_CONNECT              134
#define IDD_PP_SAVESETTINGS             135
#define IDB_BITMAP_DISCONNECT           135
#define IDR_ACCELERATOR_CARTESIAN       136
#define IDD_DIALOG_MAPPINGFUNCTION      137
#define IDR_MENU_TERM                   140
#define IDR_MENU_BATCH                  141
#define IDI_IMOTE                       142
#define IDR_ACCELERATOR_TERM            143
#define IDR_ACCELERATOR_TERM1           144
#define IDR_ACCELERATOR_BATCH           144
#define IDD_IMOTEBATCH                  144
#define IDD_IMOTESTATUS                 145
#define IDC_COMBO_COMPORT               1000
#define IDC_BUTTON_CONNECT              1001
#define IDC_EDIT_COMMAND                1002
#define IDC_EDIT_COMMAND2               1003
#define IDC_EDIT_NUMBYTES               1003
#define IDC_BUTTON_SENDCOMMAND          1004
#define IDC_BUTTON_SENDBYTES            1005
#define IDC_BUTTON_CLEAR_BUFFER         1006
#define IDC_RICHEDIT_OUTPUT             1009
#define IDC_RICHEDIT_TEMP               1010
#define IDC_BUTTON_SETTINGS             1011
#define IDC_EDIT1                       1012
#define IDC_LIST1                       1013
#define IDC_BUTTON1                     1014
#define IDC_BUTTON2                     1015
#define IDC_CHECK_MAGICNUMBER           1016
#define IDC_CHECK_FRAGMENTLENGTH        1017
#define IDC_CHECK_CHANNELID             1018
#define IDC_CHECK_16BITDATA             1019
#define IDC_COMBO_MAGICNUMBER           1020
#define IDC_COMBO_CHANNELID             1021
#define IDC_COMBO_FRAGMENTLENGTH        1022
#define IDC_EDIT_MAGICNUMBER_VALUE      1023
#define IDC_STATIC_ASSIGNMENTBOX        1024
#define IDC_EDIT_MINRANGE               1027
#define IDC_EDIT_MAXRANGE               1028
#define IDC_BUTTON_SENDBREAK            1029
#define IDC_COMBO_DISPLAYED_IMOTE       1034
#define IDC_STATIC_DISPLAYED_IMOTE      1035
#define IDC_STATIC_COM_NUM              1038
#define IDC_STATIC_DETACHED             1039
#define IDC_BUTTON_WINDOW_BUFFER        1041
#define IDC_BUTTON_TERM_CLEAR_BUFFER    1042
#define IDC_BUTTON_TERM_CONNECT         1043
#define IDC_BUTTON_TERM_SENDBREAK       1044
#define IDC_STATIC_TERM_DETACHED        1045
#define IDC_STATIC_TERM_COM_NUM         1046
#define IDC_STATIC_ABOUT_COPY           1047
#define IDC_BUTTON_TERM_SENDFILE        1047
#define IDC_STATIC_ABOUT_VER            1048
#define IDC_STATIC_TERM_ADDR            1048
#define IDC_STATIC_ABOUT_DEV            1049
#define IDC_STATIC_ABOUT_IMOTE          1050
#define IDC_BUTTON_TERM_EXECUTE         1050
#define IDC_CHECK_TERM_TEXT_FILE        1051
#define IDC_RICHEDIT_TERM_FILE          1052
#define IDC_STATIC_STATUS_BNUMBER       1054
#define IDC_RICHEDIT_TERM_ADDR          1054
#define IDC_STATIC_STATUS_VNUMBER       1055
#define IDC_PROGRESS_STATUS_VERIFY      1056
#define IDC_PROGRESS_STATUS_BURN        1057
#define IDC_STATIC_BATCH_BNUMBER        1058
#define IDC_PROGRESS_BATCH_BURN         1059
#define IDC_STATIC_BATCH_VNUMBER        1060
#define IDC_PROGRESS_BATCH_VERIFY       1061
#define IDC_RICHEDIT_BATCH_FILE         1062
#define IDC_BUTTON_BATCH_BURN           1063
#define IDC_STATIC_BATCH_TNUMBER        1064
#define IDC_PROGRESS_BATCH_TOTAL        1065
#define IDC_BUTTON_BATCH_BURN2          1066
#define IDC_BUTTON_BATCH_ABORT          1066
#define ID_EDIT_NEWWIN                  32771
#define ID_FILE_SAVE32772               32772
#define ID_FILE_SAVEAS                  32773
#define ID_FILE_EXIT                    32774
#define ID_HELP_ABOUT                   32775
#define ID_EDIT_OPTIONS                 32776
#define ID_Menu                         32777
#define ID_EDIT_CONNECT                 32778
#define ID_EDIT_SETMAPPINGFUNCTION      32780
#define ID_VIEW                         32782
#define ID_VIEW_ZOOMIN                  32783
#define ID_VIEW_ZOOMOUT                 32784
#define ID_EDIT_TEST                    32785
#define ID_VIEW32788                    32788
#define ID_VIEW_SMOOTH                  32789
#define ID_EDIT_TESTNEWLIST             32790
#define ID_EDIT_ECHO                    32791
#define ID_TERM_EDIT_ECHO               32797
#define ID_TERM_EDIT_CONNECT            32798
#define ID_TERM_FILE_SAVE               32799
#define ID_TERM_FILE_SAVEAS             32800
#define ID_TERM_EDIT_CLEAR_BUFFER       32803
#define ID_TERM_FILE_HIDE               32805
#define ID_TERM_EDIT_COPY               32806
#define ID_TERM_EDIT_SENDFILE           32809
#define ID_TERM_FILE_OPENFILE           32810
#define ID_BATCH_FILE_OPENFILE          -32717
#define ID_BATCH_FILE_HIDE              32820
#define ID_BATCH_EDIT_BURN              32821
#define ID_BATCH_FILE_CLOSE             32825
#define ID_BATCH_EDIT_ABORT             32826
#define ID_TERM_EDIT_EXECUTE            32830

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32831
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
