PLATFORMS=telos telosb micaz 
COMPONENT ?= PongC
include ../Makerules

#TOS = $(shell ncc -print-tosdir)
#PACKAGE = net.tinyos.oscope
#APP = .
#MIG = mig java

# List of message classes to build
#MSGS = PongMsg.java PingMsg.java

#INITIAL_TARGETS = $(MSGS)
#OTHER_CLEAN = cleanmig

#ROOT = $(TOS)/../tools/java
#include $(ROOT)/Makefile.include

#PongMsg.java:
#	$(MIG) -java-classname=PongMsg $(APP)/PongMsg.h PongMsg -o $@
#	$(JAVAC) $@

#PingMsg.java:
#	$(MIG) -java-classname=PingMsg $(APP)/PongMsg.h PingMsg -o $@
#	$(JAVAC) $@
