APP_CFLAGS := -DIS_RECEIVER
APP_INCLUDE := 
APP_OBJS := DiffNodeInc/DataCache.o \
	DiffNodeInc/DataEntry.o \
	DiffNodeInc/DiffTable.o \
	DiffNodeInc/GradientEntry.o \
	DiffNodeInc/InterestEntry.o \
	DiffNodeInc/LocationEntry.o \
	DiffNodeInc/CodeEntry.o \
	DiffNodeInc/LocalCode.o
#	DiffNodeInc/sp_debug.o	

include ../Makeinclude

