ROOT = ../../..
MODULE = tossim_util
NAMES = File Heap
TARGET = lib

LOCAL_INCLUDEPATH =
LOCAL_LIBRARYPATH =
LOCAL_LIBRARIES = boost_filesystem-gcc

include $(ROOT)/src/Makefile.defines

include $(ROOT)/src/Makefile.rules

