COMPONENT=FlashBridgeViewerTestC

# Choose a flash type:
CFLAGS += -I../../media/at45db
#CFLAGS += -I../../media/msp430
#CFLAGS += -I../../media/avr

# Other FlashBridge include directories:
CFLAGS += -I../../interfaces

# Utils
CFLAGS += -I../../../../../tos/lib/State
CFLAGS += -I../../../../../tos/lib/GenericCrc
CFLAGS += -I../../../../../tos/lib/Leds

# If you use Boomerang, comment this line out:
CFLAGS += -I../../../../../tos/lib/Transceiver

# If you use Boomerang, uncomment these lines out:
#CFLAGS += -DSTM25P_BOOMERANG_VERSION
#CFLAGS += -I../../../../tos/lib/sptransceiver

include $(MAKERULES)


 
