# $Id: Makefile,v 1.12 2005/04/04 10:04:05 husq Exp $
XBOWROOT=%T/../contrib/xbow/tos
XBOWBETAROOT=%T/../contrib/xbow/beta/tos

COMPONENT=XSensorMTS300
SENSORBOARD=mts310
PFLAGS= -I$(XBOWROOT)/interfaces  -I$(XBOWROOT)/system  -I$(XBOWROOT)/platform/$(PLATFORM) -I$(XBOWROOT)/AXStack/$(PLATFORM) -I$(XBOWROOT)/lib -I$(XBOWROOT)/sensorboards/$(SENSORBOARD)

include ../MakeXbowlocal
include ${TOSROOT}/tools/make/Makerules

