COMPONENT=TestBlackbookDictionaryC

# Choose a flash type:
#CFLAGS += -I../../media/AT45DB
CFLAGS += -I../../media/STM25P

# Standard include directories:
CFLAGS +=  -I../../ -I../../core -I../../interfaces -I../../boot
CFLAGS += -I../../../../tos/lib/State

# Compiler optimizer flag - try it with and without:
CFLAGS += -Os

# If you use Boomerang, uncomment this line:
#CFLAGS += -DSTM25P_BOOMERANG_VERSION

include $(MAKERULES)



