enum {
  DB_NUM_NEIGHBOR = 3,
  DB_DECISION_INVALID = 1,
  DB_DECISION_BEST_INVALID_OLD_LINK_BAD = 2,
  DB_DECISION_BEST_INVALID_OLD_OK = 3,
  DB_DECISION_OLD_INVALID_BEST_LINK_BAD = 4,
  DB_DECISION_OLD_INVALID_BEST_OK = 5,
  DB_DECISION_NOT_BETTER_OLD_LINK_BAD = 6,
  DB_DECISION_NOT_BETTER = 7,
  DB_DECISION_BOTH_LINK_BAD = 8,
  DB_DECISION_BEST_BETTER_BEST_LINK_BAD = 9,
  DB_DECISION_SWITCH = 10,
  // for use for the old version
  DB_DECISION_SAME_PARENT = 11,
  DB_DECISION_BAD_PARENT_LINK = 12,
  PLOT_NUM_NEIGHBOR = DB_NUM_NEIGHBOR
};



