# $Id: Makefile,v 1.8 2005/03/31 07:15:06 husq Exp $

include Makefile.component
#include ../../MakeXbowlocal

# Automatically add certain command-line goals:
GOALS += mesh freq
TOSMAKE_PATH = ${TOSROOT}/contrib/xbow/tools/make
include ${TOSROOT}/tools/make/Makerules
