#ifndef __TRIGGERFUNCTIONS_H__
#define __TRIGGERFUNCTIONS_H__

enum
  {
    TRIGGER_GT=0,
    TRIGGER_LT,
    TRIGGER_RMS_GT,
    TRIGGER_RMS_LT,
    TRIGGER_ABSOLUTE_GT,
    TRIGGER_ABSOLUTE_LT,
    TRIGGER_POSEDGE,
    TRIGGER_NEGEDGE
  };

#endif
