PFLAGS := -Ischedroute -I%T/../contrib/ucb/tos/lib/BufferManager/CircleQueue -I%T/../contrib/ucb/tos/lib/BufferManager/BufferPool -I%T/../contrib/ucb/tos/lib/BufferManager/QueuedASend

COMPONENT=TestMHQASend
include ../Makerules

