#ifndef ERRORTOLEDS_H
#define ERRORTOLEDS_H

enum {
    AM_ERRORTOLEDSMSG = 10,
};

typedef struct ErrorToLedsMsg {
    uint16_t sourceAddr;
    uint16_t errorCode;
} ErrorToLedsMsg;

#define ERRORTOLEDS_ERRORTEST 1
#define ERRORTOLEDS_SAMPLING1 200
#define ERRORTOLEDS_FETCH1 300
#define ERRORTOLEDS_FETCH2 301
#define ERRORTOLEDS_SAMPLINGTODATASTORE1 400
#define ERRORTOLEDS_DATASTORE1 500
#define ERRORTOLEDS_DATASTORE2 501
#define ERRORTOLEDS_DATASTORE3 502
#define ERRORTOLEDS_DATASTORE4 503
#define ERRORTOLEDS_DATASTORE5 504
#define ERRORTOLEDS_DATASTORE6 505
#define ERRORTOLEDS_DATASTORE7 506
#define ERRORTOLEDS_DATASTORE8 507
#define ERRORTOLEDS_DATASTORE9 508
#define ERRORTOLEDS_DATASTORE10 509
#define ERRORTOLEDS_DATASTORE11 510
#define ERRORTOLEDS_DATASTORE12 511
#define ERRORTOLEDS_TESTPERFORMANCE1 600
#define ERRORTOLEDS_TESTPERFORMANCE2 601
#define ERRORTOLEDS_TESTPERFORMANCE3 602
#define ERRORTOLEDS_TESTPERFORMANCE4 603
#define ERRORTOLEDS_TESTPERFORMANCE5 604
#define ERRORTOLEDS_TESTPERFORMANCE6 605
#define ERRORTOLEDS_TESTPERFORMANCE7 606
#define ERRORTOLEDS_TESTPERFORMANCE8 607
#define ERRORTOLEDS_TESTPERFORMANCE9 608
#define ERRORTOLEDS_ERUPTIONDETECTOR1 701
#define ERRORTOLEDS_ERUPTIONDETECTOR2 702
#define ERRORTOLEDS_ERUPTIONDETECTOR3 703
#define ERRORTOLEDS_ERUPTIONDETECTOR4 704
#define ERRORTOLEDS_ERUPTIONDETECTOR5 705
#define ERRORTOLEDS_ERUPTIONDETECTOR6 706
#define ERRORTOLEDS_ERUPTIONDETECTOR7 707
#define ERRORTOLEDS_ERUPTIONDETECTOR8 708
#define ERRORTOLEDS_ERUPTIONDETECTOR9 709
#define ERRORTOLEDS_ERUPTIONDETECTOR10 710
#define ERRORTOLEDS_ERUPTIONDETECTOR11 711
#define ERRORTOLEDS_ERUPTIONDETECTOR12 712
#define ERRORTOLEDS_DRIVER1 800
#define ERRORTOLEDS_DRIVER2 801


#endif
