/*									tab:4
 *
 *
 * "Copyright (c) 2000 and The Regents of the University 
 * of California.  All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice and the following
 * two paragraphs appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF
 * CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
 *
 * Authors:		Jason Hill
 *
 *
 */

TOS_MODULE MOTE_TEST;


ACCEPTS{
	char MOTE_TEST_INIT(void);
};

HANDLES{
	TOS_MsgPtr AM_msg_handler_5(TOS_MsgPtr data);
	TOS_MsgPtr AM_msg_handler_6(TOS_MsgPtr data);
	void MOTE_TEST_SUB_CLOCK(void);
	char MOTE_TEST_SUB_DATA_READY(int data);
};

USES{
	char MOTE_TEST_SUB_SEND_MSG(char addr,char type, TOS_MsgPtr data);
	char MOTE_TEST_SUB_POWER(char mode);
	char MOTE_TEST_SUB_INIT();
	char MOTE_TEST_SUB_CLOCK_INIT(char interval, char scale);
	char ROUTE_DATA_INIT();
	char MOTE_TEST_SUB_READ(char port);
	char PHOTO_PWR(char mode);
	char ROUTE_LED1_OFF();
	char ROUTE_LED1_ON();
	char ROUTE_LED1_TOGGLE();
	char ROUTE_LED2_OFF();
	char ROUTE_LED2_ON();
	char ROUTE_LED2_TOGGLE();
	char ROUTE_LED3_OFF();
	char ROUTE_LED3_ON();
	char ROUTE_LED3_TOGGLE();
	char MOTE_TEST_SUB_LED_INIT();
};

