/*									tab:4
 *
 *
 * "Copyright (c) 2000 and The Regents of the University 
 * of California.  All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice and the following
 * two paragraphs appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF
 * CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
 *
 * Authors:		Philip Levis
 *
 * This application component tests a few floating point operations
 * and outputs the results to the UART. It can be used to determine
 * the accuracy of floating point emulation on the mote CPU.
 */

TOS_MODULE TEST_FP;


ACCEPTS{
	char TEST_INIT(void);
	char TEST_START(void);
};

HANDLES{
	char TEST_SEND_DONE(TOS_MsgPtr data);
	void TEST_CLOCK(void);
};
USES{
	char TEST_SUB_SEND_MSG(short addr,char type, TOS_MsgPtr data);
	char TEST_SUB_POWER(char mode);
	char TEST_SUB_INIT();
	char TEST_SUB_CLOCK_INIT(char interval, char scale);
	char TEST_LED1_OFF();
	char TEST_LED1_ON();
	char TEST_LED1_TOGGLE();
	char TEST_LED2_OFF();
	char TEST_LED2_ON();
	char TEST_LED2_TOGGLE();
	char TEST_LED3_OFF();
	char TEST_LED3_ON();
	char TEST_LED3_TOGGLE();
	char TEST_SUB_LED_INIT();
};

