COMPONENT=TransmitterAppC
#COMPONENT=ReceiverAppC
CFLAGS=-I$(TOSDIR)/lib/UltrasonicRanging -I$(TOSDIR)/lib/UltrasonicRanging/HPLUART -DUART_SYNC
SENSORBOARD=micasb
PLATFORMS=mica2dot
include ../Makerules

