COMPONENT=AppSleep
PFLAGS=-I%T/lib/Counters
#PFLAGS+=-I../../contrib/ucb/tos/CC1000Pulse
include ../../../../apps/Makerules
CFLAGS += -DUSE_LOW_POWER_LISTENING -DCC1K_DEFAULT_FREQ=0x1 -DMEASURE_STATS 
# -DUSE_LPL

