#!/bin/bash
#/* $Id: labinstall,v 1.1 2003/03/17 02:43:20 wetoasis Exp $ */
#/*////////////////////////////////////////////////////////*/
#/**
# * Author: Terence Tong, Alec Woo
# */
#/*////////////////////////////////////////////////////////*/


MOTES="c62b262
c62b27a
c62b267
c62b257
c62b255
c62b260
c62b27c
c62b279
c627f34
c62b27e
c62b263
c62b26b
c62b264
c62b261"

EXTRA_PARAM="-dprog=stk500 -dpart=ATmega128"


FINAL_LIST=$MOTES

# address, node id
function download() {
	HOSTNAME=$1.research.intel-research.net
	
	echo ">>> Programming mote $HOSTNAME ..."
	echo ">>> Setting Fuse Bit ..."
	uisp -v=0 $EXTRA_PARAM -dhost=$HOSTNAME --wr_fuse_e=fd
	sleep 1
	echo ">>> Setting Mote Id To $2 ..."
	set-mote-id build/mica/main.srec build/mica/main.srec.out $2
	sleep 1
	echo ">>> Erasing ..."
	uisp $EXTRA_PARAM -dhost=$HOSTNAME --erase
	sleep 1
	echo ">>> Loading ...."
	uisp $EXTRA_PARAM -dhost=$HOSTNAME --upload if=build/mica/main.srec.out 

}

function downloadAll() {
    COUNTER=1
    for MOTE in $FINAL_LIST
    do
	download $MOTE $COUNTER
	let "COUNTER+=1"
    done
}

# start node id
function downloadPartial() {
    COUNTER=1
    for MOTE in $FINAL_LIST
    do
	if (("$COUNTER" >= "$1"))
	then
	    download $MOTE $COUNTER
	fi
	let "COUNTER+=1"
    done


}



# address
function ping() {
	HOSTNAME=$1.research.intel-research.net
	echo ">>> Pinging $HOSTNAME ..."
        /cygdrive/c/WINDOWS/system32/ping -n 1 $HOSTNAME
}

function pingAll() {
    for MOTE in $FINAL_LIST
    do
	ping $MOTE
    done
}

# address
function erase() {
	HOSTNAME=$1.research.intel-research.net
	echo ">>> Erasing $HOSTNAME ..."
	uisp $EXTRA_PARAM -dhost=$HOSTNAME --erase
}


function eraseAll() {
    for MOTE in $FINAL_LIST
    do
	erase $MOTE
    done
}

# start node id
function erasePartial() {
    COUNTER=1
    for MOTE in $FINAL_LIST
    do
	if (("$COUNTER" >= "$1"))
	then
	    erase $MOTE
	fi
	let "COUNTER+=1"
    done
}


# tablename, address
function listen() {
    echo ">>> Forking Receiver For $MOTE ..."
    java Receiver network $1 $2 &
}

# address, node id
if [ "$1" = "download" ]
then
    download $2 $3
fi

if [ "$1" = "downloadAll" ]
then
    downloadAll
fi

# start node id
if [ "$1" = "downloadPartial" ]
then
    downloadPartial $2
fi

# address
if [ "$1" = "ping" ]
then
    ping $2
fi

if [ "$1" = "pingAll" ]
then
    pingAll
fi

# address
if [ "$1" = "erase" ]
then
    erase $2
fi

if [ "$1" = "eraseAll" ]
then
    eraseAll
fi

# node id
if [ "$1" = "erasePartial" ]
then
    erasePartial $2
fi

# table, address
if [ "$1" = "listen" ]
then
    listen $2 $3
fi


