COMPONENT=TestHumidity
SENSORBOARD=mep401ca

XBOWROOT=%T/../contrib/xbow/tos
PFLAGS= -I$(XBOWROOT)/sensorboards/$(SENSORBOARD) -I$(TOSROOT)/tos/sensorboards/micawb

include $(TOSROOT)/apps/Makerules

