COMPONENT=TestYao
#COMPONENT=TestGeo
SENSORBOARD=micasb

PFLAGS = -I../../lib/location -I../../lib/neighborhood -I../../lib/sharedvar -I../../lib/collective -I../../lib/network -I../../../tossim

include ../Makerules
