/*									tab:4
 *  mic_test.h - Main component for simple application that blinks the LEDs
 *
 * "Copyright (c) 2000 and The Regents of the University 
 * of California.  All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice and the following
 * two paragraphs appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF
 * CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
 *
 * Authors:  Alec Woo
 *
 * This application simply blinks the leds with each clock interrupt.  It
 * outputs the value of a three bit counter onto the LEDS.
 *
 */

TOS_MODULE USE_MIC;

ACCEPTS{
	char USE_MIC_INIT(void);
	char USE_MIC_START(void);
};

HANDLES{
	void USE_MIC_CLOCK_EVENT(void);
	char USE_MIC_DATA_EVENT(short data);
	char USE_MIC_MIC_TONE_DETECTED(void);
	char USE_MIC_DATA_SEND_DONE(char success);
	char USE_MIC_DATA_RECV_DONE(char data, char success);
};

USES{
	char USE_MIC_SUB_INIT(char interval, char scale);
	char USE_MIC_UART_INIT();
	char USE_MIC_MIC_INIT();
	char USE_MIC_MIC_PWR(char mode);
	char USE_MIC_MIC_MUX_SEL(char select);
	char USE_MIC_POT_ADJUST(char data);
	char USE_MIC_GET_CONTINUOUS_DATA(void);
	char USE_MIC_GET_DATA(void);
	char USE_MIC_SET_SAMPLING_RATE(char rate);
	char USE_MIC_SEND_DATA(char data);
	char USE_MIC_SET_SAMPLING(char rate);
        char USE_MIC_LEDy_on();
        char USE_MIC_LEDy_off();
	char USE_MIC_LEDy_TOGGLE();
        char USE_MIC_LEDr_on();
        char USE_MIC_LEDr_off();
        char USE_MIC_LEDg_on();
        char USE_MIC_LEDg_off();
};

SIGNALS{
};

