all: getenv.dll

getenv.dll: net_tinyos_util_Env.h net_tinyos_util_Env.c
	gcc -shared -ogetenv.dll -mno-cygwin "-I$(JDK)/include" "-I$(JDK)/include/win32" -D_JNI_IMPLEMENTATION -Wl,--kill-at net_tinyos_util_Env.c

install: getenv.dll
	install --group=SYSTEM --mode=775 getenv.dll "$(JNI)"

rpminstall: getenv.dll
	install -d "$(prefix)/lib/tinyos"
	install getenv.dll "$(prefix)/lib/tinyos"

clean:
	rm -rf getenv.dll 
