COMPONENT=TestTimeSyncC
SENSORBOARD=micasb

PFLAGS=-I %T/lib/Util -I%T/lib/TinyDB -I%T/../beta/TinierDB/ -I%T/lib/MintRoute -I%T/lib/Queue  -fno-strict-aliasing

MSG_SIZE=49
include ../../../apps/Makerules
