COMPONENT = TestRealTimeSamplesC

include $(SPAULDINGSRC)/Makefile.in
include $(SPAULDINGSRC)/sampling/Makefile.in
include $(SPAULDINGSRC)/realTimeSamples/Makefile.in

#CFLAGS += -DPRINTFUART_ENABLED

include $(MAKERULES)

