ifndef NCC
NCC = ${NC2MOMLLIB_NESC}/bin/ncc
endif

NC2MOMLLIB_OUTPUTDIR = ${TOSROOT}
NC2MOMLLIB_INPUTDIR = \
	${TOSDIR}/lib \
	${TOSDIR}/system \
	${TOSDIR}/platform \
	${TOSDIR}/sensorboards

MAKERULES = ./Makerules
include ./Makerules
