enum {
  KEY_TESTRUN_START_CODE = 0,
  KEY_TESTRUN_STOP_CODE = 1,

  KEY_RADIOREGION_TIMER_RATE = 2,
  KEY_RADIOREGION_TIMER_PENDING_COUNT = 3,
  KEY_RADIOREGION_AGE_THRESHOLD = 4,
  KEY_RADIOREGION_MAX_OUTSTANDING_GETS = 5,
  KEY_RADIOREGION_REDUCE_TIMEOUT = 6,

  KEY_YAOREGION_TS_GET_DELAY = 7,
  KEY_YAOREGION_WAIT_INVALIDATION_TIMEOUT = 8,
  KEY_YAOREGION_WAIT_INVALIDATION_COUNT = 9,
  KEY_YAOREGION_GET_LOCATION_TIMEOUT = 10,

  KEY_QUEUEDSEND_MAX_RETRANSMIT_COUNT = 11,
  KEY_QUEUEDSEND_TIMER_RATE = 12,

  KEY_KNEARESTREGION_MAX_NEIGHBORS = 13,

  KEY_SPANTREEREGION_TIMER_RATE = 2,
  KEY_SPANTREEREGION_TIMER_PENDING_COUNT = 3,
  KEY_SPANTREEREGION_MAX_NEIGHBORS = 13,

  KEY_ADAPTIVEREDUCE_QUALITY_TARGET = 14,

};
