ROOT = ../..
MODULE = tossim
NAMES = Event EventQueue Eeprom PageEeprom AdcModel RfmModel SpatialModel StateModel
TARGET = lib

LOCAL_INCLUDEPATH =
LOCAL_LIBRARYPATH =
LOCAL_LIBRARIES = pthread

include $(ROOT)/src/Makefile.defines

include $(ROOT)/src/Makefile.rules

