# This application assumes the 13192EVB board and the accelerometer sensor
# board.

PLATFORMS=evb13192 
SENSORBOARD=accelerometer
COMPONENT=TestAccelerometer
#ENVIRONMENT=SimpleMac

include ../Makerules

