#For these classes to be used, one must add contrib/shockfish/tools/java to the CLASSPATH

PACKAGE = net.tinyos.package

TOS = $(shell ncc -print-tosdir)
ROOT = $(TOS)/../tools/java

include $(ROOT)/Makefile.include
