# When building consider using the following options:
#
#    SSID=string                   Set the SSID of the access point
#    IP=x.x.x.x                    Set the IP address of the access point
#    HOST_IP=x.x.x.x   	           Uses wired operation and sets HOST_IP='x.x.x.x'
#    
# For example:
#
#    make SSID="CRL" IP='16.11.5.30' telosb       ---> Builds Wireless
#    make HOST_IP='16.11.5.50' IP='16.11.5.51' telosb             ---> Builds Wired
# 
# This code requires a TelosB with a 2411 serial number and install Temp/Humidity sensors

COMPONENT=HumidityTemp

USE_IP=True
SELECT_WIRED_OR_WIRELESS=True

include ../Makerules


