COMPONENT=RfmToLeds
PFLAGS=-I%T/lib/Counters
XBOWROOT=%T/../contrib/xbow/tos

PFLAGS += -I$(XBOWROOT)/platform/$(PLATFORM) -I$(XBOWROOT)/AXStack/$(PLATFORM)

include ../MakeXbowlocal
include $(TOSROOT)/tools/make/Makerules

