COMPONENT=Surge
#SENSORBOARD=basicsb
#SENSORBOARD=micasb


PFLAGS= -I%T/../contrib/eyes/tos/lib/MultiHopRSSI -I%T/lib/Queue -I%T/lib/Broadcast
#PFLAGS= -I%T/lib/ReliableRoute -I%T/lib/Queue -I%T/lib/Broadcast

include ../MakeEyes
