ROOT = ../../..
MODULE = tossim_tests
NAMES = Eeprom PageEeprom AdcModel RfmModel SpatialModel StateModel
TARGET = exe

LOCAL_INCLUDEPATH =
LOCAL_LIBRARYPATH =
LOCAL_LIBRARIES = tossim

include $(ROOT)/test/Makefile.defines

include $(ROOT)/test/Makefile.rules
