/*									tab:2
 *
 *
 * "Copyright (c) 2000 and The Regents of the University 
 * of California.  All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice and the following
 * two paragraphs appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF
 * CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
 *
 * Authors:		Nelson Lee
 *
 * A test of the NARPRO protocol component using fake data.
 */

TOS_MODULE NARPRO_TEST;


ACCEPTS{
	char NARPRO_TEST_INIT(void);
	char NARPRO_TEST_START(void);
};

HANDLES{
	void NARPRO_TEST_CLOCK(void);
};

USES{
	char NARPRO_TEST_SEND(char* data, char len);
	char NARPRO_TEST_RED_LED_TOGGLE();
	char NARPRO_TEST_GREEN_LED_TOGGLE();
	char NARPRO_TEST_YELLOW_LED_TOGGLE();
	char NARPRO_TEST_YELLOW_LED_ON();
	char NARPRO_TEST_YELLOW_LED_OFF();
	char NARPRO_TEST_SUB_LED_INIT();
	char NARPRO_TEST_CLOCK_INIT(char interval, char scale);
	char NARPRO_TEST_SUB_ACTIVE();

};


