MIG=mig java -target=mica2
TASKINCLUDES = -I $(TOS)/lib/Commands -I $(TOS)/lib/Util -I $(TOS)/lib/Attributes -I $(TOS)/lib/TinyDB -I $(TOS)/sensorboards/micasb -I $(TOS)/lib/TinyDB/Aggregates -I $(TOS)/lib/MintRoute -I $(TOS)/lib/Queue -I$(TOS)/lib/FS/ -DBOARD_MICAWB -I $(TOS)/../apps/TASKApp
INCLUDES = $(TASKINCLUDES)
include MakeInclude
