include ../Makelocal
FIREBOARD_PATH += -I$(MTS420CA)/sensors/intersema5534ap
LOCAL_PATH += $(FIREBOARD_PATH)

COMPONENT=testintersema

PFLAGS := $(LOCAL_PATH) $(LOCAL_DEFINES) $(PFLAGS)


include $(TOSROOT)/apps/Makerules

