COMPONENT=LocalizationAppC
DEFAULT_LOCAL_GROUP=0xdd

#CFLAGS= -I../include \
#-I$(TOSROOT)/beta/I2C/system \
#-I$(TOSROOT)/beta/I2C/platform/mica2dot \
#-I$(TOSROOT)/beta/I2C/platform/mica2 \
#-I$(TOSROOT)/beta/I2C/platform/mica \
#-I$(TOSROOT)/beta/I2C/platform/avrmote \
#-I$(TOSROOT)/beta/I2C/types \
#-I$(TOSROOT)/beta/I2C/interfaces 
CONTRIBDIR=../..

include ../MakeCalamari

