COMPONENT = MetricsMote

# Keeping Radio Channel Close to Deployed Network Channel (0x11)
# so transmission range is similar
CC2420_CHANNEL := 0x12
DEFAULT_LOCAL_GROUP := 0x0b

GOALS+=nescDecls

PFLAGS += -I$(TOSDIR)/../contrib/nestfe/nesc/lib/Metrics

include $(TOSDIR)/../apps/Makerules

