COMPONENT=Aggregator
CFLAGS+=  -I../../lib/TimeSync -I../../lib/GridRouting -I../../lib/ReliableComm -I../../lib/MagSensor -I../../lib/AcousticSensor -I./ -I../../interfaces
DEFAULT_LOCAL_GROUP := 0x7d

include ../../../../../apps/Makerules
