COMPONENT=Surge
SENSORBOARD=micasb

PFLAGS= -I../../tos/platform/mica2 -I../../tos/CC1000RadioPulse -I../../tos/lib/ReliableRoute_Low_Power -I%T/lib/Queue -I%T/lib/Broadcast

include ../MakeXbowlocal
include ${TOSROOT}/apps/Makerules
