/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TestMsg'
 * message type.
 */

package com.rincon.testharness.messages;

public class TestMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 6;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 115;

    /** Create a new TestMsg of size 6. */
    public TestMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TestMsg of the given data_length. */
    public TestMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestMsg with the given data_length
     * and base offset.
     */
    public TestMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestMsg using the given byte array
     * as backing store.
     */
    public TestMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TestMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TestMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestMsg embedded in the given message
     * at the given base offset.
     */
    public TestMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestMsg embedded in the given message
     * at the given base offset and length.
     */
    public TestMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TestMsg> \n";
      try {
        s += "  [param=0x"+Long.toHexString(get_param())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [result=0x"+Long.toHexString(get_result())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [cmd=0x"+Long.toHexString(get_cmd())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: param
    //   Field type: long, unsigned
    //   Offset (bits): 0
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'param' is signed (false).
     */
    public static boolean isSigned_param() {
        return false;
    }

    /**
     * Return whether the field 'param' is an array (false).
     */
    public static boolean isArray_param() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'param'
     */
    public static int offset_param() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'param'
     */
    public static int offsetBits_param() {
        return 0;
    }

    /**
     * Return the value (as a long) of the field 'param'
     */
    public long get_param() {
        return (long)getUIntElement(offsetBits_param(), 32);
    }

    /**
     * Set the value of the field 'param'
     */
    public void set_param(long value) {
        setUIntElement(offsetBits_param(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'param'
     */
    public static int size_param() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'param'
     */
    public static int sizeBits_param() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: result
    //   Field type: short, unsigned
    //   Offset (bits): 32
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'result' is signed (false).
     */
    public static boolean isSigned_result() {
        return false;
    }

    /**
     * Return whether the field 'result' is an array (false).
     */
    public static boolean isArray_result() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'result'
     */
    public static int offset_result() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'result'
     */
    public static int offsetBits_result() {
        return 32;
    }

    /**
     * Return the value (as a short) of the field 'result'
     */
    public short get_result() {
        return (short)getUIntElement(offsetBits_result(), 8);
    }

    /**
     * Set the value of the field 'result'
     */
    public void set_result(short value) {
        setUIntElement(offsetBits_result(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'result'
     */
    public static int size_result() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'result'
     */
    public static int sizeBits_result() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: cmd
    //   Field type: short, unsigned
    //   Offset (bits): 40
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'cmd' is signed (false).
     */
    public static boolean isSigned_cmd() {
        return false;
    }

    /**
     * Return whether the field 'cmd' is an array (false).
     */
    public static boolean isArray_cmd() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'cmd'
     */
    public static int offset_cmd() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'cmd'
     */
    public static int offsetBits_cmd() {
        return 40;
    }

    /**
     * Return the value (as a short) of the field 'cmd'
     */
    public short get_cmd() {
        return (short)getUIntElement(offsetBits_cmd(), 8);
    }

    /**
     * Set the value of the field 'cmd'
     */
    public void set_cmd(short value) {
        setUIntElement(offsetBits_cmd(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'cmd'
     */
    public static int size_cmd() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'cmd'
     */
    public static int sizeBits_cmd() {
        return 8;
    }

}
