COMPONENT=TSTestAppC
DEFAULT_LOCAL_GROUP=0xdd
TINYSEC=true
CNTRIBDIR=../..
PFLAGS := $(PFLAGS) -I../radio
CFLAGS := $(CFLAGS) \
	-I$(CNTRIBDIR)/tinysec-route/routeinterpret \
	-I$(CNTRIBDIR)/PEGSensor/croute \
	-I$(CNTRIBDIR)/PEGSensor/PEGSensor

include ../MakeTinySec

