COMPONENT=TinyDBApp
SENSORBOARD=micasb

PFLAGS=-I %T/lib/Util -I%T/lib/Attributes -I%T/lib/Commands -I%T/lib/TinyDB -I%T/lib/MintRoute -I%T/lib/Queue  -I%T/lib/FS -I%T/lib/TinyDB/Aggregates -fno-strict-aliasing

MSG_SIZE=49
include ../Makerules


