COMPONENT=UltrasoundTransmitterC
CFLAGS=-I../../tos/interfaces -I../../../calamari/micaUltrasoundLib -I../../../calamari/micaRangingApp -I../../tos/lib/Ranging
CFLAGS+=-DUART_SYNC

ifndef MAKESYSTEMC
MAKESYSTEMC := ../../../../contrib/SystemC/MakeSystemC
endif

include $(MAKESYSTEMC)


