// $Id: sensorboard.h,v 1.1 2004/11/22 14:33:34 husq Exp $
TOSH_ALIAS_OUTPUT_ONLY_PIN(ACCEL_LOW_CLK, PW0);
TOSH_ALIAS_OUTPUT_ONLY_PIN(ACCEL_LOW_CS, PW1);
TOSH_ALIAS_OUTPUT_ONLY_PIN(ACCEL_HIGH_CLK, PW2);
TOSH_ALIAS_OUTPUT_ONLY_PIN(ACCEL_HIGH_CS, PW3);

TOSH_ALIAS_OUTPUT_ONLY_PIN(TEMP_CS, PW4);
TOSH_ALIAS_OUTPUT_ONLY_PIN(TEMP_SCK, PW6);


TOSH_ALIAS_PIN(ACCEL_LOW_VERTICAL, INT0);
TOSH_ALIAS_PIN(ACCEL_LOW_HORIZONTAL, INT1);
TOSH_ALIAS_PIN(ACCEL_HIGH_HORIZONTAL, INT2);
TOSH_ALIAS_PIN(ACCEL_HIGH_VERTICAL, INT3);

TOSH_ALIAS_PIN(TEMP_SIO, PW5);

