# Top-level Makefile for contrib/nestfe/java/net/tinyos/drain_msgs

# We do all subdirectories (to allow for optional package installation)
SUBDIRS = $(shell find . -maxdepth 1 -type d | tail +2 | grep -v /CVS)

ROOT = ../../..
include $(ROOT)/Makefile.include
