# $Id: Makefile,v 1.1 2004/11/15 03:42:18 husq Exp $
XBOWROOT=%T/../contrib/xbow/tos
XBOWBETAROOT=%T/../contrib/xbow/beta/tos

COMPONENT=TestSensor
SENSORBOARD=mts310

PFLAGS= -I$(XBOWBETAROOT)/lib/Xee -I$(XBOWROOT)/interfaces  -I$(XBOWROOT)/system  -I$(XBOWROOT)/platform/$(PLATFORM) -I$(XBOWROOT)/lib -I$(XBOWROOT)/sensorboards/$(SENSORBOARD)

include ../MakeXbowlocal
include ${TOSROOT}/tools/make/Makerules

