
#
#  define -DUSE_HOSTMOTE_SENS to enable sensing features
#  define -DUSE_HOSTMOTE_SYNC to enable sync on external int
#


APP_CFLAGS = \
	-DRFM_COUNTER_NUM=ETC_8 \
	-DCLOCK_COUNTER_NUM=ITC_16 \
	-DCLOCK_FRC=32 
#	-DRFM_TIMESTAMP_SUPPORT \
#	-DUSE_HOSTMOTE_SENS \
#	-DUSE_HOSTMOTE_SYNC \
#	-DLED_DEBUG


include ../Makeinclude

