#!/bin/sh

# handle symbolic links
SCRIPT=$0
if [ -L "$SCRIPT" ]; then
	SCRIPT=`/bin/ls -l $SCRIPT | sed 's/.*-> //'`
fi

BASE="${SCRIPT%/*}"

which cygpath 2>/dev/null >/dev/null && BASE="`cygpath -m "$BASE"`"

if [ -f $BASE/simdriver.jar ]; then
	EXEC="-jar $BASE/simdriver.jar"
else
	EXEC="net.tinyos.sim.SimDriver"
fi

ARGS="-Dpython.cachedir=/tmp/jython.cache -DDBG=$DBG -DSIMDBG=$SIMDBG $EXEC"

echo java $ARGS "${@}"
exec java $ARGS "${@}"
