/**
 * @author Mike Grimmer
 */

enum {
  TOSH_ACTUAL_PHOTO_PORT = 1,
  TOSH_ACTUAL_MIC_PORT = 2, 
  TOSH_ACTUAL_ACCEL_X_PORT = 3, 
  TOSH_ACTUAL_ACCEL_Y_PORT = 4,
  TOSH_ACTUAL_MAG_X_PORT = 5, 
  TOSH_ACTUAL_MAG_Y_PORT = 6,  
  TOSH_ACTUAL_PIR_PORT = 7
};

enum {
  TOS_ADC_PHOTO_PORT = 1,
  TOS_ADC_MIC_PORT = 2,
  TOS_ADC_ACCEL_X_PORT = 3,
  TOS_ADC_ACCEL_Y_PORT = 4,
  TOS_ADC_MAG_X_PORT = 5,
  TOS_ADC_MAG_Y_PORT = 6,
  TOS_ADC_PIR_PORT = 7
};

enum {
  TOS_MAG_POT_ADDR = 0,
  TOS_MIC_POT_ADDR = 1,
  TOS_PIR_POT_ADDR = 2
};

TOSH_ALIAS_PIN(PHOTO_CTL, INT1);
TOSH_ALIAS_PIN(ACCEL_CTL, PW0);
TOSH_ALIAS_OUTPUT_ONLY_PIN(MIC_CTL, PW3);
TOSH_ALIAS_PIN(LPF_CTL, PW7);
TOSH_ALIAS_PIN(LPF_CLK, PWM1A);
TOSH_ALIAS_OUTPUT_ONLY_PIN(SOUNDER_CTL, PW2)
TOSH_ALIAS_PIN(MAG_CTL, PW5);
TOSH_ALIAS_OUTPUT_ONLY_PIN(MIC_MUX_SEL, PW6);


