COMPONENT=AbstractMate
CFLAGS=-I%T/lib/VM/components -I%T/lib/VM/opcodes -I%T/lib/VM/contexts -I%T/lib/VM/types -I%T/lib/VM/interfaces -I%T/lib/Route -I%T/lib/Queue 
MSG_SIZE=36
include ../Makerules

