# $Id: Makefile,v 1.1 2004/11/22 14:20:45 husq Exp $

XBOWROOT=%T/../contrib/xbow/tos

COMPONENT=TestSensorGGB
SENSORBOARD=ggbacltst

PFLAGS= -I$(XBOWROOT)/interfaces  -I$(XBOWROOT)/system  -I$(XBOWROOT)/platform/$(PLATFORM) -I$(XBOWROOT)/lib -I$(XBOWROOT)/sensorboards/$(SENSORBOARD)
include ../MakeXbowlocal
include ${TOSROOT}/tools/make/Makerules

