PLATFORMS=mica2
COMPONENT=Surge
SENSORBOARD=micasb

PFLAGS= -I../../tos/lib/RouteFMAC -I../../tos/lib/Queue -I../../tos/lib/Broadcast -I../../tos/lib/FunnelingMAC

include ../Makelocal
include ../Makerules
